### ISSUE TITLE
all funds gone through 3.9 XMR in fee

### ISSUE THREAD

**Issue by kvnkmth** [monero-project/monero#8447] opened 2022-07-20 23:29 UTC
Sent a transaction as usual but did realize my funds we all gone through the fee.
transaction hash 2d97b227942d46aead4ae7dd788adc2a2e83b8540f9e6a5f70f13dad67724e9a

**Comment by selsta** [comment] 2022-07-20 23:46
Which version are you using?

**Comment by kvnkmth** [comment] 2022-07-20 23:49
sadly 0.17.1.9

**Comment by selsta** [comment] 2022-07-20 23:50
We have added a high fee warning, plus we have scanned all remote nodes multiple times and were not able to find whatever node is this behind this. 

![](https://user-images.githubusercontent.com/7697454/165557782-af28867d-a759-43b9-8a31-d2dea0fa157c.png)

If you use v0.17.1.9 that fee warning sadly doesn't exist yet. We hoped that people would upgrade due to the auto updater :/

**Comment by selsta** [comment] 2022-07-20 23:53
How much XMR are still left in your wallet?

**Comment by kvnkmth** [comment] 2022-07-20 23:57
nothing actually. its zero

**Comment by kvnkmth** [comment] 2022-07-20 23:58
> How much XMR are still left in your wallet?



> We have added a high fee warning, plus we have scanned all remote nodes multiple times and were not able to find whatever node is behind this.
> 
> ![](https://user-images.githubusercontent.com/7697454/165557782-af28867d-a759-43b9-8a31-d2dea0fa157c.png)
> 
> If you use v0.17.1.9 that fee warning sadly doesn't exist yet. We hoped that people would upgrade due to the auto updater :/

i wish i upgraded

**Comment by selsta** [comment] 2022-07-20 23:58
That's.. bizarre. What wallet mode are you using in Settings -> Info?

**Comment by kvnkmth** [comment] 2022-07-21 00:02
it was in simple mode

**Comment by selsta** [comment] 2022-07-21 00:03
And that happened a couple weeks ago, right? Can you make a screenshot from the transaction inside the GUI?

**Comment by kvnkmth** [comment] 2022-07-21 00:09
i remember the transaction took ages to send. and the first confirmation took like 30 mins

**Comment by kvnkmth** [comment] 2022-07-21 00:18
![fee](https://user-images.githubusercontent.com/6536172/180103783-96ad221c-ad92-41f3-9b06-880a0a2153f0.png)
How do i recover the funds?

**Comment by selsta** [comment] 2022-07-21 00:21
What does it say in the top left corner: `XMR :.??`

**Comment by kvnkmth** [comment] 2022-07-21 00:29
thats the balance why bruh

**Comment by selsta** [comment] 2022-07-21 00:34
Because I have never seed `:.??` as a balance. It's either `?.??` or a number. To figure out what's going on I need to know your exact remaining balance.

Regarding "recovering" funds, this was 2 weeks ago and whatever mining pool has mined this transaction has already paid out the fee to miners.

**Comment by kvnkmth** [comment] 2022-07-21 00:37
its zero 0.0000 this is version 0.18 am running

**Comment by kvnkmth** [comment] 2022-07-21 00:43
but the balance is zero. its just that i cropped the screenshot
its all i had left
which pool mined it?

**Comment by selsta** [comment] 2022-07-21 02:27
Did you intend to send 0.5 XMR or did you intend to send your whole balance?

**Comment by kvnkmth** [comment] 2022-07-21 09:16
i sent 0.5 xmr. and it arrived but fee was 3.9 and didnt realize it till yesterday

**Comment by Cactii1** [comment] 2022-07-21 19:22
> Because I have never seen `:.??` as a balance. It's either `?.??` or a number.

This isn't answered by "I cropped the screenshot".

**Comment by Cactii1** [comment] 2022-07-21 19:24
Let's get the obvious answered first.

Where did you download your wallet from?
Do you still have the archive and can you verify the hash on that archive?

**Comment by Cactii1** [comment] 2022-07-21 19:28
If you sent it 14 days ago you didn't send it with the software you're currently using (v0.18)

**Comment by kvnkmth** [comment] 2022-07-21 21:13
i sent it with v0.17.1.9 
got it from getmonero.org
sha256sum edc47b1540510640a40e8d52ad4ab3a6220f935e881fd65b02ccce94a28c3fa2

**Comment by kvnkmth** [comment] 2022-07-21 21:15
> i sent it with v0.17.1.9 got it from getmonero.org sha256sum edc47b1540510640a40e8d52ad4ab3a6220f935e881fd65b02ccce94a28c3fa2

its for monero-gui-install-win-x64-v0.17.1.9.exe

**Comment by Cactii1** [comment] 2022-07-21 21:23
Alright, that's the correct hash.

Maybe this makes the case to make it so simple mode remembers where it gets its information from when forming a transaction.

**Comment by kvnkmth** [comment] 2022-07-22 07:30
how do i recover the funds

**Comment by Cactii1** [comment] 2022-07-22 15:05
> how do i recover the funds

Your funds are not recoverable.

**Comment by kvnkmth** [comment] 2022-07-22 15:14
great

**Comment by plowsof** [comment] 2022-07-28 19:01
Just to clarify. 
- fee of 3.954
- sent 0.5
- total = 0.5 + 3.954 = 4.454
- if your balance before sending this transaction was exactly 4.454 then your wallet balance is now zero

can you confirm?

**Comment by Cactii1** [comment] 2022-07-28 19:06
That would be very strange that the fee would be exactly enough to empty the wallet of all funds.

**Comment by fugbixer** [comment] 2022-08-10 02:52
>That would be very strange that the fee would be exactly enough to empty the wallet of all funds.

> its for monero-gui-install-win-x64-v0.17.1.9.exe

1.could it be a pointer usage which leads malware to get the value
2.blocks all other than the malicious node
3. manipulates the memory of the monero gui  fee when creating the transaction to steal funds ? 

could the node operator somehow obtain the fees?

@selsta 

good counter to show the high fees warning but it is not noob safe enough. 
maybe adding a won't proceed when the xmr fee is above a certain unreasonable amount like 0.1+ 
depending on how serious this issue could be / become

**Comment by kvnkmth** [comment] 2022-08-10 12:09
> Just to clarify.
> 
> * using a custom gui wallet which shows balance as ":".?? instead of "?":??
> * fee of 3.954
> * sent 0.5
> * total = 0.5 + 3.954 = 4.454
> * if your balance before sending this transaction was exactly 4.454 then your wallet balance is now zero
> 
> can you confirm?

no the fee did not wipe the whole wallet.
it left around 0.5xmr
so the gui wallet is compromised?

**Comment by plowsof** [comment] 2022-08-10 14:50
"exactly".... "around" .. posting the wrong txid initially, and you're using a modified version of the gui .. please close this issue nothing can be done for you. 

To me this looks like a bad attempt to try and 'get a refund' for something that didn't happen to you OR you really did download a compromised version of the Monero GUI and there is still nothing we can do, and i apologise for the accusation.

**Comment by kvnkmth** [comment] 2022-08-10 15:35
> "exactly".... "around" .. posting the wrong txid initially, and you're using a modified version of the gui .. please close this issue nothing can be done for you.
> 
> To me this looks like a bad attempt to try and 'get a refund' for something that didn't happen to you OR you really did download a compromised version of the Monero GUI and there is still nothing we can do, and i apologise for the accusation.

Which transaction are you talking about.
My funds are gone through the fee and you just speculate am lying?
you don't even try to check with me properly.
the hashes for gui wallet all checked out
check well this is my transaction `2d97b227942d46aead4ae7dd788adc2a2e83b8540f9e6a5f70f13dad67724e9a`
you are sitting on the edge of an attack may be @fugbixer is right

**Comment by fugbixer** [comment] 2022-08-11 07:24
@kvnkmth please calm down, losing money sucks for everyone. since its crypto you cant get a refund. 
so @plowsof ur the first who brought this up. he asking if there is a way to recover the funds, we told him no there is not.
end of story. 

@selsta made a solution  which is good, but i think can be improved. 

>good counter to show the high fees warning but it is not noob safe enough.
maybe adding a won't proceed when the xmr fee is above a certain unreasonable amount like 0.1+

so the thread can be closed and we can hope the fix will be in the next wallet release so that this does not happen anymore.
no one is responsible for devices security beside the owner, for the wallet issue we are thankful that it got reported so in case some is trying to manipulate the wallet / or its somehow caused by a bug, it will not happen in the future.

**Comment by kvnkmth** [comment] 2022-08-11 10:15
@fugbixer cool i hope no one else will fall for this bug

**Closed** 2022-08-11 10:15 UTC

**Comment by selsta** [comment] 2022-08-11 15:46
@fugbixer we will likely hardcode a couple community run nodes so that this issue doesn't even happen in the first place.

**Comment by fugbixer** [comment] 2022-08-11 18:01
please make it fail safe with a fallback mode in case that none of the community nodes can be reached since they could become a primary target of ddos attacks / censorship.
