### ISSUE TITLE
 Can not forwarding 18080 port  

### ISSUE THREAD

**Issue by maogo** [monero-project/monero#5197] opened 2019-02-25 09:24 UTC
HI: 
 I am runing a full node wallet on my home network and forward the 18080 port to the local IP.
 But not long ago,Almost all ISP cancelled the default dynamic public IP,Only see a private network IP on 
 the  router and the daemon  output incoming connections error.
 It looks like 18080 port forwarding failed,I guess the problem comes from ISP,If true,I wanna know if it 
 could be coded to solve this problem for example NAT(Network Address Translator),We will get more sync 
 nodes.

**Comment by jindouyunz** [comment] 2019-02-25 09:28
Anyone helps? it's a common issue in China, preventing people to run full node here, appreciate much.

**Comment by moneromooo-monero** [comment] 2019-02-25 10:49
If I understand correctly, the issue is that connections from the outside to your home network are impossible due to your home network not being addressable from the outside. Is that correct ?

If so, then a mitigation could be to have part of the outgoing connections jump from host to host till they find some which are not synced yet. This will ensure the "hidden" node is as useful as possible to the network in terms of serving blockchain data.

**Comment by maogo** [comment] 2019-02-25 12:51
Right.
I can't understand “a mitigation” , how?.
**Is there an easy way to get a monero node  as a public node inside a home network?** no way? maybe i need to buy a public IP.

**Comment by moneromooo-monero** [comment] 2019-02-25 13:11
If you want to connect to it from the outside (ie, from a wallet), then you'd need some ssh magic.

If you want your node to contribute to the network by supplying historical blockchain, then currently it will kind of work on and off, if you're connecting to syncing nodes, but the change I suggested above (which requires code changes) would work for this.

**Comment by moneromooo-monero** [comment] 2019-02-26 12:49
https://github.com/monero-project/monero/pull/5199 adds those code changes I mentioned above.

**Comment by moneromooo-monero** [comment] 2019-03-21 14:36
#5199 is now merged.

For external wallet access (eg, phone wallet to home node), you can either use the Tor proxy that was added recently (see ANONYMITY_NETWORKS.md for details). Otherwise, some ssh reverse setup.

So I'll call it fixed.

+resolved

**Closed** 2019-03-21 14:41 UTC
Labels: resolved
