### ISSUE TITLE
v0.11.1.0 fails to build `make debug`

### ISSUE THREAD

**Issue by jfreeze** [monero-project/monero#2776] opened 2017-11-08 04:48 UTC
Debug build fails for version v0.11.1.0

git checkout v0.11.1.0
make debug
[elided...]
[ 92%] Building CXX object src/blockchain_utilities/CMakeFiles/blockchain_export.dir/blockchain_export.cpp.o
[ 93%] Building CXX object src/blockchain_utilities/CMakeFiles/blockchain_export.dir/bootstrap_file.cpp.o
[ 94%] Building CXX object src/blockchain_utilities/CMakeFiles/blockchain_export.dir/blocksdat_file.cpp.o
[ 95%] Linking CXX executable ../../bin/monero-blockchain-export
make[3]: Leaving directory '/home/jimfreeze/monero/build/debug'
[ 95%] Built target blockchain_export
make[3]: Entering directory '/home/jimfreeze/monero/build/debug'
Scanning dependencies of target cn_deserialize
make[3]: Leaving directory '/home/jimfreeze/monero/build/debug'
make[3]: Entering directory '/home/jimfreeze/monero/build/debug'
[ 96%] Building CXX object src/debug_utilities/CMakeFiles/cn_deserialize.dir/cn_deserialize.cpp.o
[ 97%] Linking CXX executable ../../bin/monero-utils-deserialize
../common/libcommon.so: undefined reference to `cryptonote::blockchain_db_types(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
src/debug_utilities/CMakeFiles/cn_deserialize.dir/build.make:119: recipe for target 'bin/monero-utils-deserialize' failed
make[3]: *** [bin/monero-utils-deserialize] Error 1
make[3]: Leaving directory '/home/jimfreeze/monero/build/debug'
CMakeFiles/Makefile2:1971: recipe for target 'src/debug_utilities/CMakeFiles/cn_deserialize.dir/all' failed
make[2]: *** [src/debug_utilities/CMakeFiles/cn_deserialize.dir/all] Error 2
make[2]: Leaving directory '/home/jimfreeze/monero/build/debug'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/jimfreeze/monero/build/debug'
Makefile:36: recipe for target 'debug' failed
make: *** [debug] Error 2

**Comment by moneromooo-monero** [comment] 2017-11-08 09:42
Apply a95e460c7116589b5dedf5c966cb84893fe8d521. Though you might need to apply a few more if it doesn't apply cleanly.

**Comment by erciccione** [comment] 2017-11-08 10:38
Isn't this a duplicate of #2740 ? @moneromooo-monero the same solution apply?

**Comment by moneromooo-monero** [comment] 2017-11-08 10:57
Looks like it, thanks :)

+duplicate

**Closed** 2017-11-08 11:00 UTC
Labels: duplicate
