### ISSUE TITLE
can't exit monerod on 2012 server

### ISSUE THREAD

**Issue by gbb0330** [monero-project/monero#1286] opened 2016-11-01 02:18 UTC
there is a problem with gracefully closing monerod.exe on 2012 server and 2012 server core. should be easy to reproduce, i can successfully and consistently reproduce the problem on 3 different servers.

the problem occurs if you type exit in the daemon, or if you use curl to send stop_daemon command.
the daemon hangs at p2p net loop stopped until the enter key is pressed.
see screenshot below

http://imgur.com/a/yE42B

as soon as the enter key is presses the daemon closes as expected. this creates a problem with scheduled tasks for example, i can't gracefully close the daemon unless i am physically present to press enter.

**Comment by moneromooo-monero** [comment] 2016-11-01 12:52
Are you a Windows coder ? I think I know more or less what the problem is, and how to fix it. I just need a Windows coder to find the right Windows API to replace a POSIX one, and test it :)

**Comment by gbb0330** [comment] 2016-11-01 20:34
unfortunately i am not a coder. just a sys admin

**Comment by NanoAkron** [comment] 2016-11-05 14:30
Maybe @vtnerd could help us out here?

**Comment by vtnerd** [comment] 2016-11-07 12:54
This would currently not be a priority for me, but I can try to look at it. I have only have Windows 8 with VS 2013/2015, so I have to first get mingw installed. @moneromooo-monero what POSIX function needs replacing?

**Comment by moneromooo-monero** [comment] 2016-11-07 21:16
1 - make sure you can reliably enough repro the bug, as it's apparently random-ish

2 - I'm not sure this is the reason, but it looks likely to me

3 - look in contrib/epee/include/console_handler.h, in wait_stdin_data, there's a select call ("wait till there's something to read on the fd we're passing"), which means the Linux implementation will not get into std::getline (blocking) if there's nothing to input. I think if we get into getline, the thread blocks till enter is pressed. So the trick is to replace select.

**Comment by gbb0330** [comment] 2016-11-08 22:17
here is a direct link to 2012 server core that you can use to test with (no license required). in case you need it:

http://care.dlservice.microsoft.com/dl/download/3/4/7/347A95F0-A63C-492F-BE43-F376AE30C9FE/9200.16384.WIN8_RTM.120725-1247_X64FRE_SERVERHYPERCORE_EN-US-HRM_SHV_X64FRE_EN-US_DV5.ISO

**Comment by gbb0330** [comment] 2016-11-09 20:37
confirming bug is random-ish, but its easy to reproduce, at least on my servers it happens very often.

**Comment by moneromooo-monero** [comment] 2016-11-17 22:35
I had a look on ddg and came up with https://github.com/monero-project/monero/pull/1353. Apparently it works.

**Comment by luigi1111** [comment] 2016-12-15 16:05
Fixed by #1353 (if found to be untrue, please reopen/open a new issue).

**Closed by luigi1111** 2016-12-15 16:05 UTC
