### ISSUE TITLE
monerod stuck because of "Exception: cryptonote::BLOCK_DNE"

### ISSUE THREAD

**Issue by SarshesJ** [monero-project/monero#3812] opened 2018-05-16 10:28 UTC
It seems that it happens when we meet this "Sync data returned a new top block candidate: 1573899 -> 1567592 [Your node is 6307 blocks (8 days) ahead]".

Full logs:
```
2018-05-16 10:05:25.558     7fd0d1664740        INFO    global  src/daemon/main.cpp:280 Monero 'Lithium Luna' (v0.12.0.0-master-release)
2018-05-16 10:05:25.558     7fd0d1664740        INFO    global  src/daemon/protocol.h:53        Initializing cryptonote protocol...
2018-05-16 10:05:25.558     7fd0d1664740        INFO    global  src/daemon/protocol.h:58        Cryptonote protocol initialized OK
2018-05-16 10:05:25.561     7fd0d1664740        INFO    global  src/daemon/p2p.h:63     Initializing p2p server...
2018-05-16 10:05:30.121     7fd0d1664740        INFO    global  src/daemon/p2p.h:68     p2p server initialized OK
2018-05-16 10:05:30.122     7fd0d1664740        INFO    global  src/daemon/rpc.h:63     Initializing core RPC server...
2018-05-16 10:05:30.122     7fd0d1664740        INFO    global  contrib/epee/include/net/http_server_impl_base.h:76     Binding on 127.0.0.1:18081
2018-05-16 10:05:30.122     7fd0d1664740        INFO    global  src/daemon/rpc.h:69     core RPC server initialized OK on port: 18081
2018-05-16 10:05:30.122     7fd0d1664740        INFO    global  src/daemon/core.h:86    Initializing core...
2018-05-16 10:05:30.122     7fd0d1664740        INFO    global  src/cryptonote_core/cryptonote_core.cpp:427     Loading blockchain from folder /root/.bitmonero/lmdb ...
2018-05-16 10:05:30.159     7fd0d1664740        INFO    global  src/cryptonote_core/cryptonote_core.cpp:525     Loading checkpoints
2018-05-16 10:05:31.221     7fd0d1664740        WARN    net.dns src/common/dns_utils.cpp:508    WARNING: no two valid MoneroPulse DNS checkpoint records were received
2018-05-16 10:05:31.221     7fd0d1664740        INFO    global  src/daemon/core.h:92    Core initialized OK
2018-05-16 10:05:31.221     7fd0d1664740        INFO    global  src/daemon/rpc.h:74     Starting core RPC server...
2018-05-16 10:05:31.221 [SRV_MAIN]      INFO    global  src/daemon/rpc.h:79     core RPC server started ok
2018-05-16 10:05:31.227 [SRV_MAIN]      INFO    global  src/daemon/p2p.h:78     Starting p2p net loop...
2018-05-16 10:05:32.227 [P2P2]  INFO    global  src/cryptonote_core/cryptonote_core.cpp:1386    ^[[1;33m
**********************************************************************
The daemon will start synchronizing with the network. This may take a long time to complete.

You can set the level of process detailization through "set_log <level|categories>" command,
where <level> is between 0 (no details) and 4 (very verbose), or custom category based levels (eg, *:WARNING).

Use the "help" command to see the list of available commands.
Use "help <command>" to see a command's documentation.
**********************************************************************
^[[0m
2018-05-16 10:05:33.253 [P2P2]  WARN    net.dns src/common/dns_utils.cpp:508    WARNING: no two valid MoneroPulse DNS checkpoint records were received
2018-05-16 10:05:33.588 [P2P7]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1579    ^[[1;33m
**********************************************************************
You are now synchronized with the network. You may now start monero-wallet-cli.

Use the "help" command to see the list of available commands.
**********************************************************************^[[0m
2018-05-16 10:05:45.909 [P2P6]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:310     [93.105.187.121:18080 OUT] Sync data returned a new top block candidate: 1573899 -> 1567592 [Your node is 6307 blocks (8 days) ahead]
SYNCHRONIZATION started
2018-05-16 10:05:52.363 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:124  Exception: cryptonote::BLOCK_DNE
2018-05-16 10:05:52.363 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:125  Unwound call stack:
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [1] ./monerod:__wrap___cxa_throw+0x10a [0x7fd0d1c5e1ba]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [2] ./monerod+0x51b0c9 [0x7fd0d1b890c9]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [3] ./monerod:cryptonote::BlockchainLMDB::get_block_height(crypto::hash const&) const+0x437 [0x7fd0d1b97137]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [4] ./monerod:cryptonote::BlockchainLMDB::get_block_blob[abi:cxx11](crypto::hash const&) const+0x144 [0x7fd0d1b89ea4]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [5] ./monerod:bool cryptonote::Blockchain::get_blocks<std::__cxx11::list<crypto::hash, std::allocator<crypto::hash> >, std::__cxx11::list<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cryptonote::block>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cryptonote::block> > >, std::__cxx11::list<crypto::hash, std::allocator<crypto::hash> > >(std::__cxx11::list<crypto::hash, std::allocator<crypto::hash> > const&, std::__cxx11::list<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cryptonote::block>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cryptonote::block> > >&, std::__cxx11::list<crypto::hash, std::allocator<crypto::hash> >&) const+0x1f1 [0x7fd0d1bec511]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [6] ./monerod:cryptonote::Blockchain::handle_get_objects(cryptonote::NOTIFY_REQUEST_GET_OBJECTS::request&, cryptonote::NOTIFY_RESPONSE_GET_OBJECTS::request&)+0x1de [0x7fd0d1bd369e]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [7] ./monerod:cryptonote::t_cryptonote_protocol_handler<cryptonote::core>::handle_request_get_objects(int, cryptonote::NOTIFY_REQUEST_GET_OBJECTS::request&, cryptonote::cryptonote_connection_context&)+0x18f [0x7fd0d1b4ddbf]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [8] ./monerod:int epee::net_utils::buff_to_t_adapter<cryptonote::t_cryptonote_protocol_handler<cryptonote::core>, cryptonote::NOTIFY_REQUEST_GET_OBJECTS::request, cryptonote::cryptonote_connection_context, boost::_bi::bind_t<int, boost::_mfi::mf3<int, cryptonote::t_cryptonote_protocol_handler<cryptonote::core>, int, cryptonote::NOTIFY_REQUEST_GET_OBJECTS::request&, cryptonote::cryptonote_connection_context&>, boost::_bi::list4<boost::_bi::value<cryptonote::t_cryptonote_protocol_handler<cryptonote::core>*>, boost::arg<1>, boost::arg<2>, boost::arg<3> > > >(cryptonote::t_cryptonote_protocol_handler<cryptonote::core>*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::_bi::bind_t<int, boost::_mfi::mf3<int, cryptonote::t_cryptonote_protocol_handler<cryptonote::core>, int, cryptonote::NOTIFY_REQUEST_GET_OBJECTS::request&, cryptonote::cryptonote_connection_context&>, boost::_bi::list4<boost::_bi::value<cryptonote::t_cryptonote_protocol_handler<cryptonote::core>*>, boost::arg<1>, boost::arg<2>, boost::arg<3> > >, cryptonote::cryptonote_connection_context&)+0x24f [0x7fd0d19da13f]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [9] ./monerod:int cryptonote::t_cryptonote_protocol_handler<cryptonote::core>::handle_invoke_map<cryptonote::cryptonote_connection_context>(bool, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cryptonote::cryptonote_connection_context&, bool&)+0x2aa [0x7fd0d19e983a]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [10] ./monerod:int nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> >::handle_invoke_map<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> >(bool, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context>&, bool&)+0xc2 [0x7fd0d19e9ac2]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [11] ./monerod:nodetool::node_server<cryptonote::t_cryptonote_protocol_handler<cryptonote::core> >::notify(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context>&)+0x50 [0x7fd0d19e9e90]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [12] ./monerod:epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> >::handle_recv(void const*, unsigned long)+0x4ad [0x7fd0d1b6a0ad]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [13] ./monerod:epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::handle_read(boost::system::error_code const&, unsigned long)+0x1f8 [0x7fd0d1b81ea8]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [14] ./monerod:void boost::asio::detail::strand_service::dispatch<boost::asio::detail::binder2<boost::_bi::bind_t<void, boost::_mfi::mf2<void, epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > > > >, boost::arg<1> (*)(), boost::arg<2> (*)()> >, boost::system::error_code, unsigned long> >(boost::asio::detail::strand_service::strand_impl*&, boost::asio::detail::binder2<boost::_bi::bind_t<void, boost::_mfi::mf2<void, epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > > > >, boost::arg<1> (*)(), boost::arg<2> (*)()> >, boost::system::error_code, unsigned long>&)+0x7a [0x7fd0d1b4adfa]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [15] ./monerod:boost::asio::detail::completion_handler<boost::asio::detail::rewrapped_handler<boost::asio::detail::binder2<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, boost::_bi::bind_t<void, boost::_mfi::mf2<void, epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > > > >, boost::arg<1> (*)(), boost::arg<2> (*)()> >, boost::asio::detail::is_continuation_if_running>, boost::system::error_code, unsigned long>, boost::_bi::bind_t<void, boost::_mfi::mf2<void, epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > > > >, boost::arg<1> (*)(), boost::arg<2> (*)()> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long)+0x188 [0x7fd0d1b4b268]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [16] ./monerod:void boost::asio::detail::strand_service::dispatch<boost::asio::detail::rewrapped_handler<boost::asio::detail::binder2<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, boost::_bi::bind_t<void, boost::_mfi::mf2<void, epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > > > >, boost::arg<1> (*)(), boost::arg<2> (*)()> >, boost::asio::detail::is_continuation_if_running>, boost::system::error_code, unsigned long>, boost::_bi::bind_t<void, boost::_mfi::mf2<void, epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > > > >, boost::arg<1> (*)(), boost::arg<2> (*)()> > > >(boost::asio::detail::strand_service::strand_impl*&, boost::asio::detail::rewrapped_handler<boost::asio::detail::binder2<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, boost::_bi::bind_t<void, boost::_mfi::mf2<void, epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > > > >, boost::arg<1> (*)(), boost::arg<2> (*)()> >, boost::asio::detail::is_continuation_if_running>, boost::system::error_code, unsigned long>, boost::_bi::bind_t<void, boost::_mfi::mf2<void, epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > > > >, boost::arg<1> (*)(), boost::arg<2> (*)()> > >&)+0x226 [0x7fd0d1b4b656]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [17] ./monerod:boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, boost::_bi::bind_t<void, boost::_mfi::mf2<void, epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > > > >, boost::arg<1> (*)(), boost::arg<2> (*)()> >, boost::asio::detail::is_continuation_if_running> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long)+0x250 [0x7fd0d1b4b930]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [18] ./monerod:boost::asio::detail::epoll_reactor::descriptor_state::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long)+0x1f4 [0x7fd0d19692e4]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [19] ./monerod:epee::net_utils::boosted_tcp_server<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >::worker_thread()+0x854 [0x7fd0d1b2fb54]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [20] ./monerod+0x9870c5 [0x7fd0d1ff50c5]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [21] /lib/x86_64-linux-gnu/libpthread.so.0+0x76ba [0x7fd0d0d236ba]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163      [22] /lib/x86_64-linux-gnu/libc.so.6:clone+0x6d [0x7fd0d0a5941d]
2018-05-16 10:05:52.368 [P2P5]  INFO    stacktrace      src/common/stack_trace.cpp:163
```
Environment: ubuntu:16.04 in docker
Command: ./monerod --rpc-bind-port 18081 --log-file /var/log/monerod.log
Software version: 0.12.0.0 Lithium Luna downloaded from https://getmonero.org/downloads/#linux

**Comment by dEBRUYNE-1** [comment] 2018-05-16 16:14
See #3284

**Comment by moneromooo-monero** [comment] 2018-05-16 18:02
These two things are unrelated. The sync problems are fixed in current release-0.12. The spammy DNE logs are also silenced where appropriate.

**Comment by baryluk** [comment] 2018-05-16 22:17
Ok. I guess I posted this in the wrong bug, as I didn't seen the other one, it was recently closed. But I do use 0.12, so I shouldn't be getting these messages probably.

**Comment by moneromooo-monero** [comment] 2018-05-16 22:28
You're likely using v0.12.0.0 rather than release-0.12, right ?

**Comment by SarshesJ** [comment] 2018-05-17 02:53
@moneromooo-monero  yes, i'm using v0.12.0.0.
But where can i get release-0.12, should I build the release-0.12 manually?

**Comment by moneromooo-monero** [comment] 2018-05-17 07:29
You do this:

git clone https://github.com/monero-project/monero/
cd monero
git checkout release-0.12
make

If you already have a monero tree, you can skip the first step.
You need to build it, yes. There are no binaries with these fixes yet.

**Comment by stoffu** [comment] 2018-05-17 07:54
If first time cloning, you'd need `git clone --recursive https://github.com/monero-project/monero/`

**Comment by stoffu** [comment] 2018-05-18 06:41
As the error message says:

> recompile with -fPIC

The error is caused by your system's `libgtest` not being compiled with -fPIC. The gtest source is bundled in the Monero repository, so you can simply uninstall your system's gtest and build the bundled one.

**Comment by SarshesJ** [comment] 2018-05-18 08:57
I followed this answer https://stackoverflow.com/a/38297422/8157756, and add `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` to `cmake/internal_utils.cmake` under `/usr/src/gtest` and then execute
```
root@bc2cb1d5ea2d:/usr/src/gtest# pwd
/usr/src/gtest
root@bc2cb1d5ea2d:/usr/src/gtest# ls cmake/internal_utils.cmake 
cmake/internal_utils.cmake
root@bc2cb1d5ea2d:/usr/src/gtest# cmake .
root@bc2cb1d5ea2d:/usr/src/gtest# make
```
then I can compile monero bins successfully. But it still depends on libzmq3-dev libunbound-dev. And when i build monero with `make release-static`, I will get this error
```
[ 88%] Building CXX object src/wallet/CMakeFiles/wallet_rpc_server.dir/wallet_rpc_server.cpp.o
[ 89%] Linking CXX executable ../../bin/monero-wallet-rpc
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libboost_chrono.a(chrono.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libboost_chrono.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/wallet/CMakeFiles/wallet_rpc_server.dir/build.make:133: recipe for target 'bin/monero-wallet-rpc' failed
make[3]: *** [bin/monero-wallet-rpc] Error 1
make[3]: Leaving directory '/root/monero-recursive/build/release'
CMakeFiles/Makefile2:2367: recipe for target 'src/wallet/CMakeFiles/wallet_rpc_server.dir/all' failed
make[2]: *** [src/wallet/CMakeFiles/wallet_rpc_server.dir/all] Error 2
make[2]: Leaving directory '/root/monero-recursive/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/monero-recursive/build/release'
Makefile:68: recipe for target 'release-static' failed
make: *** [release-static] Error 2
```
Does it mean that I need to rebuild libboost? Anyway, I think i've got a workable monerod :).
Thank you guys. Thank you very much.

**Closed** 2018-05-19 10:38 UTC

**Comment by SarshesJ** [comment] 2018-05-19 10:39
The new compiled monerod just works fine. Close the Issue.
