### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Lynx-fx8300** [monero-project/monero#9618] opened 2024-12-14 13:47 UTC
I do everything according to the instructions, but during assembly I always get an error:

```
 implicit declaration of function 'strdup'; did you mean 'strcmp'? [-Wimplicit-function-declaration]
   60 |         elt->descURL = strdup(dev->descURL);
      |                        ^~~~~~
      |                        strcmp
/monero/external/miniupnp/miniupnpc/listdevices.c:60:22: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
   60 |         elt->descURL = strdup(dev->descURL);
      |                      ^
```

**Comment by selsta** [comment] 2024-12-14 14:17
Please share more information. Which OS are you using? Can you share the exact steps you used to build?

**Comment by Lynx-fx8300** [comment] 2024-12-14 14:37
I use arch,
First I installed all the necessary dependencies with the command:
`sudo pacman -Syu --needed base-devel cmake boost openssl zeromq libpgm unbound libsodium libunwind xz readline expat gtest python3 ccache doxygen graphviz qt5-tools hidapi libusb protobuf systemd`

Then I cloned the monero repository:
`git clone --recursive https://github.com/monero-project/monero`

After cloning, I going to the directory with the command:
`cd monero && git submodule init && git submodule update`

And I started building:
`make`

**Comment by selsta** [comment] 2024-12-14 15:50
Appears to be a duplicate of #9359.

The solution is to update the miniupnp submodule, like for example in #9367, or to use the workaround https://github.com/monero-project/monero/issues/9359#issuecomment-2308956945

**Closed by selsta** 2024-12-14 15:50 UTC
Labels: more info needed
