### ISSUE TITLE
monerod frequently gets stuck syncing

### ISSUE THREAD

**Issue by B6Zip** [monero-project/monero#3713] opened 2018-04-26 19:59 UTC
Every couple of days it seems that monero daemon will stop retrieving new blocks and will be sitting at the same block height until the daemon is restarted.

**Comment by moneromooo-monero** [comment] 2018-04-26 22:02
Once this happens, post the output of "sync-info" and "status".
Then set_log 1,net*:DEBUG
Then wait a bit and post the resulting log (fpaste.org or pastebin.mozilla.org or paste.debian.net).

**Comment by Onefox** [comment] 2018-04-26 22:41
I have the same Problem.
At some point i don't see the yellow block messages anymore after a deamon restart.
![image](https://user-images.githubusercontent.com/1709259/39335114-f4f4f432-49b1-11e8-849f-960e7100e6fa.png)
Here is the set_log output after that:
https://paste.fedoraproject.org/paste/Szh-FyNuY1zVWwNa6v6X9Q

**Comment by moneromooo-monero** [comment] 2018-04-27 14:07
Once this happens, post the output of "sync_info" and "status".
And "diff" too.

**Comment by Onefox** [comment] 2018-04-27 14:14
@moneromooo-monero  what do you mean with diff?
The sync and status info can be seen on the screenshot right?

**Comment by Onefox** [comment] 2018-04-27 15:50
The other node had to be restaret.
But i have the same problem on a testnode:
here the print_cn:
> 
> print_cn
> Remote Host                   Peer id             Support Flags       Recv/Sent (inactive,sec)      State                    Livetime(sec)       Down (kB/s) Down(now)     Up (kB/s) Up(now)
> 
> INC 62.210.104.109:24790      fe74bb70413ebbe0    1                   675176(5)/10919174(5)         state_normal             270                 2           0             39        69
> INC 31.174.56.239:56178       14f02ca5ba6336be    1                   8449(43)/8145580(41)          state_normal             274                 0           0             29        290
> INC 54.38.82.8:54474          00a3043c706759d5    1                   147620(41)/56076(41)          state_normal             416                 0           2             0         0
> INC 183.89.212.241:59479      5ad01cd24433ff32    1                   365521(40)/387040(41)         state_normal             2994                0           0             0         0
> OUT 81.169.162.150:28080      b190ef88ec604c13    1                   2231639(11)/1486779(11)       state_normal             11808               0           0             0         0
> OUT 78.2.110.212:28080        be2e871ebd2d7790    1                   4534476(5)/1496132(5)         state_normal             11813               0           0             0         0
> INC 5.9.100.248:42738         5b4f28fe30cb7479    1                   7459792(2)/918355830(2)       state_normal             11874               0           0             75        104
> INC 118.193.19.166:60040      ef7ab19a70764599    1                   4535786(19)/1516063(19)       state_normal             11881               0           0             0         0
> OUT 212.53.140.36:28080       90a7396f8404834c    1                   4561732(32)/1503792(32)       state_normal             11915               0           2             0         0
> OUT 217.64.127.195:30996      bd0eece0e0b8e9d4    1                   4542993(30)/1423227(30)       state_normal             11915               0           0             0         0
> OUT 114.167.8.26:28080        82cbdd613c42042b    1                   5125600(10)/210593238(10)     state_normal             11713               0           0             17        34
> INC 104.1.221.229:64208       c61bc07ee954ebf8    1                   518595(13)/943483(13)         state_normal             7198                0           0             0         0
> OUT 198.199.122.75:28080      a3a408945b8762d8    1                   4560648(7)/1480831(7)         state_normal             11921               0           0             0         0
> INC 95.156.96.238:63544       ae103be4916dafd7    1                   415462(4)/63936952(4)         state_normal             2505                0           0             24        35
> OUT 5.9.150.112:28080         985ec51ddba0956f    1                   4538602(41)/1480004(41)       state_normal             11926               0           2             0         0
> OUT 42.98.225.123:28080       8335a45139206c22    1                   1210317(40)/1499963(41)       state_normal             11927               0           0             0         0
> 
![image](https://user-images.githubusercontent.com/1709259/39371593-6eb4d9f0-4a42-11e8-8e88-3561957ff1b8.png)
Here the sync_info:

> sync_info
> Height: 1090169, target: 1090666 (99.9544%)
> Downloading at 6 kB/s
> 17 peers
> 62.210.104.109:24790      fe74bb70413ebbe0  1090670  0 kB/s, 0 blocks / 0 MB queued
> 31.174.56.239:56178       14f02ca5ba6336be  832822  0 kB/s, 0 blocks / 0 MB queued
> 54.38.82.8:54474          00a3043c706759d5  1090169  0 kB/s, 0 blocks / 0 MB queued
> 183.89.212.241:59479      5ad01cd24433ff32  1090169  0 kB/s, 0 blocks / 0 MB queued
> 81.169.162.150:28080      b190ef88ec604c13  1090169  0 kB/s, 0 blocks / 0 MB queued
> 78.2.110.212:28080        be2e871ebd2d7790  1090169  0 kB/s, 0 blocks / 0 MB queued
> 5.9.100.248:42738         5b4f28fe30cb7479  1066771  0 kB/s, 0 blocks / 0 MB queued
> 96.248.81.93:55028        bb27eeefc7e93fca  1090166  0 kB/s, 0 blocks / 0 MB queued
> 118.193.19.166:60040      ef7ab19a70764599  1090169  0 kB/s, 0 blocks / 0 MB queued
> 212.53.140.36:28080       90a7396f8404834c  1090169  2 kB/s, 0 blocks / 0 MB queued
> 217.64.127.195:30996      bd0eece0e0b8e9d4  1090169  2 kB/s, 0 blocks / 0 MB queued
> 114.167.8.26:28080        82cbdd613c42042b  1057047  0 kB/s, 0 blocks / 0 MB queued
> 104.1.221.229:64208       c61bc07ee954ebf8  1090169  0 kB/s, 0 blocks / 0 MB queued
> 198.199.122.75:28080      a3a408945b8762d8  1090169  0 kB/s, 0 blocks / 0 MB queued
> 95.156.96.238:63544       ae103be4916dafd7  159792  0 kB/s, 0 blocks / 0 MB queued
> 5.9.150.112:28080         985ec51ddba0956f  1090169  2 kB/s, 0 blocks / 0 MB queued
> 42.98.225.123:28080       8335a45139206c22  1090169  0 kB/s, 0 blocks / 0 MB queued
> 0 spans, 0 MB
> 


status
Height: 1090169/1090666 (99.9%) on testnet, not mining, net hash 503 H/s, v8, up to date, 8(out)+8(in) connections, uptime 0d 3h 21m 42s

And here a log again:
https://paste.fedoraproject.org/paste/TnlowG7keP-a26oz4vij3A

**Comment by moneromooo-monero** [comment] 2018-04-27 18:36
This patch might help. Check for "Sync seems wedged, restarting" messages in the log, followed by sync restarting. It checks for 2 blocks, you may want to set this to, say, 10 for testing to make sure it's really wedged before this kicks in.

https://github.com/moneromooo-monero/bitmonero/tree/wrec

**Comment by B6Zip** [comment] 2018-04-28 18:10
https://paste.fedoraproject.org/paste/xP1NpedrQLnyTj98iuHfMA/raw

**Comment by moneromooo-monero** [comment] 2018-04-28 18:35
That one is likely fixed by https://github.com/monero-project/monero/pull/3719

**Comment by moneromooo-monero** [comment] 2018-04-29 16:02
It doesn't seem stuck here.

**Comment by Onefox** [comment] 2018-04-29 18:45
mmh, now got the last blocks again and is back on 100% sync, I keep looking ;)

**Comment by moneromooo-monero** [comment] 2018-04-29 19:25
Did you get a log with "wedged" in ?

**Comment by Onefox** [comment] 2018-05-01 12:11
Here are the new logs, with many wedged logs.
https://paste.fedoraproject.org/paste/8yNGZEwnMzzwnY9aJY7xvA

There are also the sync_info status diff and print_cn in the bottom.

The daemon is now up to date.

**Comment by moneromooo-monero** [comment] 2018-05-01 14:43
It seems like the wedged detection triggers on the "bad" chains. Unfortunate. But stoffu fixed what is probably the (or one of the) root cause in https://github.com/monero-project/monero/pull/3723

**Comment by Onefox** [comment] 2018-05-01 20:50
It still looks like I am up to date but still the wedged output is printed.
See attached screenshot.

![image](https://user-images.githubusercontent.com/1709259/39493118-f95579a0-4d91-11e8-8bcc-eb246e158423.png)

**Comment by Onefox** [comment] 2018-05-02 23:11
The problem is while the daemon is not sync, i cant use it with a wallet.... 
Is there any way around it?

**Comment by Onefox** [comment] 2018-05-03 08:25
no its still in the stage since yesterday...
Height: 1094030/1094721 (99.9%) on testnet, not mining, net hash 409 H/s, v8, up to date, 8(out)+10(in) connections, uptime 2d 6h 6m 37s

**Comment by moneromooo-monero** [comment] 2018-05-04 10:50
And you definitely have stoffu's fix ?

**Comment by Onefox** [comment] 2018-05-06 16:32
after more testing this problem doesn't occurred anymore.
This could be closed

**Comment by moneromooo-monero** [comment] 2018-05-07 18:38
https://github.com/monero-project/monero/pull/3775 fixes a second sync failure problem.

**Comment by moneromooo-monero** [comment] 2018-05-08 20:00
And http://paste.debian.net/hidden/f8496e47/ fixes a third one.

**Comment by jwm1969** [comment] 2018-05-11 14:10
I have this same issue every couple days; should we pull and compile master or the v12 tag?

**Comment by moneromooo-monero** [comment] 2018-05-11 17:36
None of the above. Use release-0.12.

**Comment by moneromooo-monero** [comment] 2018-05-16 10:26
All known sync bugs are now fixed and merged.

+resolved

**Closed** 2018-05-16 10:48 UTC
Labels: resolved
