### ISSUE TITLE
failed to deserialize keys buffer 

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero#8684] opened 2022-12-20 04:54 UTC
https://old.reddit.com/r/monerosupport/comments/zpz5zs/keys_file_cant_restore_couldnt_open_wallet/

this is the second instance I've seen of this. Old monero users getting new software and running into this with old wallet files.

and if there's 2 people that post something, that means there's millions!

someone on IRC says its probably a corrupt file.

**Comment by afungible** [comment] 2022-12-21 02:25
And which version are the users talking about? Latest is `v0.18.1.2`

Might it be a good to check the delta of `bool wallet2::load_keys_buf(..) `with previous version where this wallet file worked.
https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L4181

**Comment by selsta** [comment] 2022-12-21 02:31
Is there anyone who reported that they have a .keys file that opens with an old version and doesn't with a new version? If yes, which exact version breaks?

So far I feel like this is just a corrupted file.

**Comment by plowsof** [comment] 2022-12-23 02:28
testing with monero-wallet-cli [v0.10.0.0](https://github.com/monero-project/monero/releases/tag/v0.10.0) Sep 19, 2016:
- cli v18.1.2 opens the keys file without issue
- gui v18.1.2 will complain - but will open the wallet without issue after cli creates the cache for it (no mention of deserialize here in this particular version)
```
Error opening wallet with password:  boost::filesystem::copy_file: Invalid argument: "/home/username/Downloads/monero.linux.x64.v0-10-0-0/wallet-v0.10_2", "/home/username/Downloads/monero.linux.x64.v0-10-0-0/wallet-v0.10_2.unportable"
```

**Comment by selsta** [comment] 2023-03-10 23:28
Since there's no clear way to reproduce (@plowsof did testing) and no other reports I'll close this for now. It's highly likely simply a corrupted wallet file.

**Closed by selsta** 2023-03-10 23:28 UTC
