### ISSUE TITLE
Bitmonero not close connections

### ISSUE THREAD

**Issue by AJIekceu4** [monero-project/monero#602] opened 2016-01-07 15:33 UTC
I run public node: 

/bitmonerod --p2p-bind-ip 188.166.61.194 --p2p-bind-port 18080 --rpc-bind-ip 188.166.61.194 --rpc-bind-port 13666...
version: Monero 'Hydrogen Helix'

http://monero.net/images/graph/node_week.png
Sun 12-00 - upgrade from version v0.8.8.7-e175205 to v0.9.0.0-release. 
On this graph tcp connections to port 13666. All this connections is remain "established".
netstat -ntu | grep ESTAB | grep :13666 | awk '{print $5}' | cut -d: -f1 | sort | uniq -c | sort -nr
     **14** 171.5.241.66
      **4** 171.5.245.99
...
blablabla

171.5.241.66 - this is my own IP, i use my remote node from this IP **3 days ago**. Use 'exit' command, when i quit from wallet.
171.5.245.99 - this is my own IP, i use my remote node from this IP **2 days ago**. Use 'exit' command, when i quit from wallet.

netstat -ntu | grep ESTAB | grep :13666 | sort
tcp        0      0 188.166.61.194:13666    171.5.241.66:41626      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.241.66:41640      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.241.66:51419      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.241.66:51420      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.241.66:51452      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.241.66:51453      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.241.66:51461      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.241.66:51486      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.241.66:51487      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.241.66:51488      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.241.66:51489      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.241.66:51492      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.241.66:54915      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.241.66:54916      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.245.99:53898      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.245.99:53900      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.245.99:53901      ESTABLISHED
tcp        0      0 188.166.61.194:13666    171.5.245.99:53902      ESTABLISHED
...
blablabla

Why all this connection not closed after 2-3 days of inactive? With other service (apache) i don't see any problem with not closed connections.

**Comment by moneromooo-monero** [comment] 2016-02-06 13:39
If you run just bitmonerod, and no wallet, do you see socket leaks like this if you run repeatedly:

curl -X POST http://127.0.0.1:28081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_connections","parms":{}}' -H 'Content-Type: application/json'

Adapt the IP address and port to your RPC connection.

I don't see any leaking sockets here. Which boost version are you using ?

**Comment by AJIekceu4** [comment] 2016-02-08 01:05
After updating libboost from 1.55 to 1.59 and recompiling bitmonerod from source - seems all OK.

**Comment by moneromooo-monero** [comment] 2016-02-20 18:52
For whoever still has the bug, this is a patch that adds logs that hopefully can help. If you run with it, it needs starting the daemon with --log-level 1. It seems I can't attach it as github throws an error when I do.


diff --git a/contrib/epee/include/net/abstract_tcp_server2.inl b/contrib/epee/include/net/abstract_tcp_server2.inl
index 4fb6fa7..b828360 100644
--- a/contrib/epee/include/net/abstract_tcp_server2.inl
+++ b/contrib/epee/include/net/abstract_tcp_server2.inl
@@ -124,10 +124,13 @@ PRAGMA_WARNING_DISABLE_VS(4355)
   {
     TRY_ENTRY();
 
+    LOG_PRINT_L1("start, " << is_income  << " " << is_multithreaded);
     // Use safe_shared_from_this, because of this is public method and it can be called on the object being deleted
     auto self = safe_shared_from_this();
-    if(!self)
+    if(!self) {
+      LOG_PRINT_L1("Failed from safe_shared_from_this");
       return false;
+    }
 
     m_is_multithreaded = is_multithreaded;
 
@@ -153,6 +156,7 @@ PRAGMA_WARNING_DISABLE_VS(4355)
 
     if(m_pfilter && !m_pfilter->is_remote_ip_allowed(context.m_remote_ip))
     {
+      LOG_PRINT_L1("Remote IP not allowed");
       _dbg2("[sock " << socket_.native_handle() << "] ip denied " << string_tools::get_ip_string_from_int32(context.m_remote_ip) << ", shutdowning connection");
       close();
       return false;
@@ -160,6 +164,7 @@ PRAGMA_WARNING_DISABLE_VS(4355)
 
     m_protocol_handler.after_init_connection();
 
+    LOG_PRINT_L1("Reading some async...");
     socket_.async_read_some(boost::asio::buffer(buffer_),
       strand_.wrap(
         boost::bind(&connection<t_protocol_handler>::handle_read, self,
@@ -264,6 +269,7 @@ PRAGMA_WARNING_DISABLE_VS(4355)
     std::size_t bytes_transferred)
   {
     TRY_ENTRY();
+    LOG_PRINT_L1("handle_read " << bytes_transferred);
     //_info("[sock " << socket_.native_handle() << "] Async read calledback.");
     
     if (!e)
@@ -294,6 +300,7 @@ PRAGMA_WARNING_DISABLE_VS(4355)
                                if (delay > 0) {
                                        long int ms = (long int)(delay * 100);
                                        epee::net_utils::data_logger::get_instance().add_data("sleep_down", ms);
+    LOG_PRINT_L1("handle_read: sleeping " << ms << " ms");
                                        std::this_thread::sleep_for(std::chrono::milliseconds(ms));
                                }
                        } while(delay > 0);
@@ -328,10 +335,10 @@ PRAGMA_WARNING_DISABLE_VS(4355)
       }
     }else
     {
-      _dbg3("[sock " << socket_.native_handle() << "] Some not success at read: " << e.message() << ':' << e.value());
+      LOG_PRINT_L1("[sock " << socket_.native_handle() << "] Some not success at read: " << e.message() << ':' << e.value());
       if(e.value() != 2)
       {
-        _dbg3("[sock " << socket_.native_handle() << "] Some problems at read: " << e.message() << ':' << e.value());
+        LOG_PRINT_L1("[sock " << socket_.native_handle() << "] Some problems at read: " << e.message() << ':' << e.value());
         shutdown();
       }
     }
@@ -373,6 +380,7 @@ PRAGMA_WARNING_DISABLE_VS(4355)
     TRY_ENTRY();
 
     // Use safe_shared_from_this, because of this is public method and it can be called on the object being deleted
+    LOG_PRINT_L1("do_send: sending " << cb);
     auto self = safe_shared_from_this();
     if (!self) return false;
     if (m_was_shutdown) return false;
@@ -491,6 +499,7 @@ PRAGMA_WARNING_DISABLE_VS(4355)
 
         long int ms = 250 + (rand()%50);
         _info_c("net/sleep", "Sleeping because QUEUE is FULL, in " << __FUNCTION__ << " for " << ms << " ms before packet_size="<<cb); // XXX debug sleep
+        LOG_PRINT_L1("do_send_chunk: sleeping " << ms << " ms");
         boost::this_thread::sleep(boost::posix_time::milliseconds( ms ) );
         _dbg1("sleep for queue: " << ms);
 
diff --git a/contrib/epee/include/net/levin_protocol_handler.h b/contrib/epee/include/net/levin_protocol_handler.h
index 512ba1c..17bcd7b 100644
--- a/contrib/epee/include/net/levin_protocol_handler.h
+++ b/contrib/epee/include/net/levin_protocol_handler.h
@@ -83,6 +83,7 @@ namespace levin
   template<class t_connection_context>
        bool protocol_handler<t_connection_context>::handle_recv(const void* ptr, size_t cb)
        {
+    LOG_PRINT_L1("handle_recv " << cb);
                if(!m_config.m_pcommands_handler)
                {
                        LOG_ERROR("Command handler not set!");
@@ -135,6 +136,7 @@ namespace levin
                                        }
 
 
+    LOG_PRINT_L1("invoking " << m_current_head.m_command << " have to return " << m_current_head.m_have_to_return_data);
                                        if(m_current_head.m_have_to_return_data)
                                        {
                                                std::string return_buff;
@@ -143,6 +145,7 @@ namespace levin
                                                m_current_head.m_have_to_return_data = false;
                                                std::string send_buff((const char*)&m_current_head, sizeof(m_current_head));
                                                send_buff += return_buff;
+    LOG_PRINT_L1("invoked " << m_current_head.m_command << ", sending back " << send_buff);
 
                                                if(!m_psnd_hndlr->do_send(send_buff.data(), send_buff.size()))
                                                        return false;

**Comment by moneromooo-monero** [comment] 2016-02-26 21:30
This may not be related to the timing out handshakes, as first thought. I can now replicate the timeouts by forcing an error path in the protocol, so the connection gets dropped, and the peer times out. This does not end up in leaking sockets though.

**Comment by moneromooo-monero** [comment] 2016-02-27 13:28
Can you please try again with the patch here: http://fpaste.org/330341/14565796/raw/

It replaces the previous patch. Run with --log-level 1

I will need to know the local port of the lingering connections (ie, as shown by netstat)

**Comment by moneromooo-monero** [comment] 2016-02-28 12:56
Possible fix: http://fpaste.org/330766/66641701/raw/

**Comment by moneromooo-monero** [comment] 2016-02-28 23:08
The above was not thread safe, this should make it so: http://fpaste.org/330911/70084414/

**Comment by moneromooo-monero** [comment] 2016-03-06 18:53
Again, a new patch which replaces the previous ones: http://fpaste.org/334868/57290305/

I think I've found a couple issues. One is fixed in this patch, the other not yet. If the logs go my way, I will fix that second one too (fixing the second one now would hide whether the first is fixed).

Please run with --log-level 1 again.

**Comment by moneromooo-monero** [comment] 2016-03-20 12:30
If anyone else wants to test, the latest patch is now at https://github.com/moneromooo-monero/bitmonero/tree/leaking-sockets and includes hyc's race fixes for db errors.

**Comment by NanoAkron** [comment] 2016-10-03 01:08
Hi @moneromooo-monero, has this been folded into core since your post or should I still pick up the patch from hyc's repo?

**Comment by moneromooo-monero** [comment] 2016-10-10 16:59
Looks like the bug fix one git merged, but not the belt and braces one, since it doesn't address the root cause.

**Comment by AJIekceu4** [comment] 2016-10-10 17:14
In the version 'Wolfram Warptangent' (v0.10.0.0-80c5de9)
Problem still exist.

**Comment by NanoAkron** [comment] 2016-12-15 20:01
@AJIekceu4 with @vtnerd's thread changes for 0.10.1, would you now try with 0.10.1 and let us know?

**Comment by vtnerd** [comment] 2016-12-15 23:19
My changes should have no affect on this (haven't completely changed the background tasking code). Although, if it somehow fixed it, celebrate.

**Comment by AJIekceu4** [comment] 2016-12-18 13:10
Hello all, i use new version 3 days and at this time no problem with connections, but may be it is just coincidence. I will test it few weeks more and make feedback here.

**Comment by AJIekceu4** [comment] 2017-01-25 19:09
I test it and unfortunally nothing change. Some connections still not closing.

**Comment by moneromooo-monero** [comment] 2017-02-19 18:43
With current master, we can have a lot better information, as the old _info type logs are now going into the normal log. Can you try again with this setting please: --log-level 2,\*net\*:3

**Comment by moneromooo-monero** [comment] 2017-02-19 18:47
Along with a note saying which IP leaked at what time if known, as the logs may be pretty large :)

**Comment by AJIekceu4** [comment] 2017-02-26 19:12
OK, i will post information later, when (if ;) detect this bug again in new version.

**Comment by AJIekceu4** [comment] 2017-02-27 16:35
netstat -ntu | grep ESTAB | grep :13666
tcp        0      0 188.166.61.194:13666    188.166.61.194:47858    ESTABLISHED
tcp        0      0 188.166.61.194:13666    188.166.61.194:47859    ESTABLISHED
tcp        0      0 188.166.61.194:47858    188.166.61.194:13666    ESTABLISHED
tcp        0      0 188.166.61.194:47859    188.166.61.194:13666    ESTABLISHED
tcp        0      0 188.166.61.194:13666    91.211.144.242:56812    ESTABLISHED

91.211.144.242 - my own IP and no active connection to rpc port between my pc and my remote node.

Log file (not from start, but from moment, when problem connection detected, port 56812, ip 91.211.144.242):
http://monero.net/logs.7z

cat /root/public_node/bitmonero.log-2017-02-27-11-23-11 | grep 56812
2017-02-27 10:33:27.906 [RPC1]  INFO    net     contrib/epee/include/net/abstract_tcp_server2.inl:270    connection type RPC 188.166.61.194:13666 <--> 91.211.144.242:56812

daemon - Monero 'Wolfram Warptangent' (v0.10.2.1-release)
wallet - Monero 'Wolfram Warptangent' (v0.10.1.0-29735c8)

**Comment by moneromooo-monero** [comment] 2017-02-28 22:40
Seems even less helpful than before. That bug's a real stinker :(

**Comment by AJIekceu4** [comment] 2017-05-07 19:54
I change server:
Old server:  3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux
New server: 4.8.0-49-generic #52~16.04.1-Ubuntu SMP Thu Apr 20 10:55:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
First server and second is VDS (common in both cases), not physical server.
And... nothing change :(

**Comment by AJIekceu4** [comment] 2017-05-12 20:39
I change server:
Old server:  3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux
New server: 4.8.0-49-generic #52~16.04.1-Ubuntu SMP Thu Apr 20 10:55:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
First server and second is VDS (common in both cases), not physical server.
And... nothing change :(

How reproduce bug:
Connect to remote node with some wallet, wait until "Background refresh thread started" and after ~5 hours type "exit" on wallet-cli. And after this on daemon side appears 1 not closed connection, like this:
> tcp        0      0 172.31.xxx.xxx:13666      91.xxx.xxx.xxx:38006    ESTABLISHED

I log all network data between my pc and remote node (via tcpflow) and check this connection data transfer (to 38006 port and from 38006 port):

This is from my pc to remote node
> GET /getheight HTTP/1.1
> Host: node.monero.net
> Content-Length: 4
> {
> }

This is answer from remote node to my pc:
> HTTP/1.1 200 Ok
> Server: Epee-based
> Content-Length: 44
> Content-Type: application/json
> Last-Modified: Fri, 12 May 2017 14:34:33 GMT
> Accept-Ranges: bytes
> 
> {
>   "height": 1308576,
>   "status": "OK"
> }

And _this is ALL network activity for this connection (port 38006) for 5 hours, while my wallet-cli was active_. Wallet-cli create separate connection only for this **one** getheight query and after few hours this connection became zombie on  daemon side ;)
If this connection get only  "height" for 1 time and not using anymore (for fully sync wallet), why it don't automatically closed by wallet-cli after successfully answer or it must be used for anything else?
As i can see, if i start sync wallet from 0, getheight  occurs every ~30 second until it fully sync and after this data transfer also stopped.

**Comment by moneromooo-monero** [comment] 2017-06-30 16:39
Can you try this branch ?
https://github.com/moneromooo-monero/bitmonero/tree/socket-error-shutdown

**Comment by AJIekceu4** [comment] 2017-07-01 13:43
Hello. I am testing it now. I will post some info after few days of using this version ;)

**Comment by AJIekceu4** [comment] 2017-07-01 19:40
After some time, i get this error and monerod stopped:

***
2017-07-01 18:31:04.956  [P2P9]  INFO    net.p2p.msg     src/cryptonote_protocol/cryptonote_protocol_handler.inl:1017    [92.135.206.9:60040 INC] Received NOTIFY_REQUEST_CHAIN (27 blocks
2017-07-01 18:31:04.975  [P2P4]  DEBUG   net     contrib/epee/include/net/levin_protocol_handler_async.h:394     [92.135.206.9:18080 OUT] LEVIN_PACKET_RECIEVED. [len=38, flags2, r?=0, cmd = 1003, v=1
2017-07-01 18:31:04.975  [P2P4]  ERROR   net.p2p src/p2p/net_node.inl:1555       [92.135.206.9:18080 OUT] back ping invoke wrong response "OK" from92.135.206.9:18080, hsh_peer_id=5b2b527fefe904a0, rsp.peer_id=c1825469c16019a6
***

This is last line,after this monerod stop work:
> [92.135.206.9:18080 OUT] back ping invoke wrong response "OK" from92.135.206.9:18080, hsh_peer_id=5b2b527fefe904a0, rsp.peer_id=c1825469c16019a6

**Comment by moneromooo-monero** [comment] 2017-10-19 16:08
Can you try https://github.com/monero-project/monero/pull/2685 ?

**Comment by AJIekceu4** [comment] 2017-10-20 17:10
Testing it now. I will report info few days later.

**Comment by AJIekceu4** [comment] 2017-10-22 15:40
Nothing change. I still can reproduce bug with this:

> How reproduce bug:
Connect to remote node with some wallet, wait until "Background refresh thread started" and after ~5 hours type "exit" on wallet-cli. And after this on daemon side appears 1 not closed connection, like this:

**Comment by dEBRUYNE-1** [comment] 2018-01-08 12:27
+bug

**Comment by hyc** [comment] 2018-02-11 22:07
I find it strange that the wallet client can cleanly exit and yet the kernel on the monerod side still sees the connection in ESTABLISHED state instead of e.g. TIME_WAIT or some other pending-close state. I suggest we turn on KEEPALIVE on the sockets; that ought to get the kernel to eventually notice the connection is dead.

**Closed** 2018-02-16 13:24 UTC
Labels: bug
