### ISSUE TITLE
Know total amount  in waiting on pending TX ( change address)

### ISSUE THREAD

**Issue by perl5577** [monero-project/monero#1993] opened 2017-04-19 06:07 UTC
Exemple simple for understand, I have only one TXNO for 100XMR.
Balance 100 Unlocked 100

I payout 70XMR to another addresse ( not already include on block).
Balance 0 Unlocked 0

Is impossible know amount 30XMR is waiting spend 

Is very difficults follow amount in wallet when make many payout.

**Comment by moneromooo-monero** [comment] 2017-04-22 11:02
This is probably caused by the bug fixed by https://github.com/monero-project/monero/pull/1989

**Comment by perl5577** [comment] 2017-04-22 20:17
No,
I want juste method for know amount in my wallet after payout.

Other exemple :
sweep_all  MYADDRESS 
balance
Balance:  0.000000000000, unlocked balance: 0.000000000000

**Comment by jonathancross** [comment] 2017-06-03 12:49
@perl5577 Can you test the latest version now that #1989 is merged?

**Comment by moneromooo-monero** [comment] 2017-08-07 17:49
+resolved

**Closed** 2017-08-07 18:12 UTC
Labels: resolved
