### ISSUE TITLE
Monerod: internal error: try to insert duplicate iterator in key_image set

### ISSUE THREAD

**Issue by ordtrogen** [monero-project/monero#3562] opened 2018-04-05 14:53 UTC
Don't know how important this is but I'll report it anyway

Windows 10 - 64-bit
monerod --version returns "Monero 'Lithium Luna' (v0.12.0.0-master-release)"

![image](https://user-images.githubusercontent.com/15184875/38373451-96efca22-38f1-11e8-8fbb-7493db892d4b.png)

**Comment by mochaccinuh** [comment] 2018-04-07 12:33
Same here on linux 64 v0.12.0.0-master-release. Got the error message shortly after I was synchronized with the network (2 minutes after).

**Comment by mocadnet** [comment] 2018-04-18 06:54
same on here on Amazon Linux AMI

**Comment by d4m4ri** [comment] 2018-04-21 14:35
This error is reproducible by removing the entire blockchain (rm -r ~/.bitmonero/) and download the entire BC again. Once it's synchronised it will show these errors ("2018-04-xx xx:xx:xx.xxx [P2P5] ERROR txpool src/cryptonote_core/tx_pool.cpp:400 internal error: try to insert duplicate iterator in key_image set") a few times. The transfer command ("transfer") in CLI works fine. I assume it's a key/hash collision due to one/several duplicates in the DB/BC.

**Comment by denisgoddard** [comment] 2018-04-24 04:42
Could these be the result of attacks from forked chains with prior key images?
https://www.coindesk.com/airdrop-attack-coming-monero-fork-condemned-as-privacy-threat/

**Comment by RichAyotte** [comment] 2018-05-17 18:36
Just adding a me too.

```
2018-05-17 18:26:44.111	[P2P8]	ERROR	txpool	src/cryptonote_core/tx_pool.cpp:400	internal error: try to insert duplicate iterator in key_image set
```
Seen on an updated Debian Sid with custom kernel.

```
$ uname -a
Linux cheetah 4.16.5-phenom #1 SMP PREEMPT Wed May 2 15:54:19 EDT 2018 x86_64 GNU/Linux
```

```
$ ./monerod 
2018-05-17 18:30:55.291	    7fea13d59bc0	INFO 	global	src/daemon/main.cpp:280	Monero 'Lithium Luna' (v0.12.0.0-master-release)
```

**Comment by moneromooo-monero** [comment] 2018-05-20 14:11
Believed fixed by https://github.com/monero-project/monero/pull/3828 (but it's hard to repro to make sure).

**Comment by johnalanwoods** [comment] 2018-06-07 18:12
Had this issue on 0.12.2: 

    2018-06-07 18:10:30.988	[P2P3]	ERROR	txpool	src/cryptonote_core/tx_pool.cpp:400	internal error: try to insert duplicate iterator in key_image set

**Comment by moneromooo-monero** [comment] 2018-06-07 19:30
With #3828 ?

**Comment by johnalanwoods** [comment] 2018-06-07 19:42
Sorry my mistake, I mistook that #3828 was already in 0.12.2 - apologies.

**Comment by moneromooo-monero** [comment] 2018-06-25 22:02
+resolved

**Closed** 2018-06-25 22:56 UTC
Labels: resolved
