### ISSUE TITLE
1024 character limit on monero-wallet-cli commands (OSX)

### ISSUE THREAD

**Issue by knaccc** [monero-project/monero#1987] opened 2017-04-17 08:39 UTC
On OSX, no more characters can be entered beyond the first 1024. This prevents more than about 9 different payees with a single transaction.

**Comment by moneromooo-monero** [comment] 2017-04-17 20:44
This works fine on Linux. The code still uses std::getline, as it always did. I don't see any mention of a limit in the documentation, and the buffer is a std::string, not a sized array.
So it looks like a Mac lower level thing.
Did it every work before on that same machine/OS ?

**Comment by knaccc** [comment] 2017-04-18 01:00
I just tried it on a prior version v0.10.0.0-release, and same problem.

**Comment by rockhouse** [comment] 2017-04-18 06:52
The problem is with the TTY line mode. It has a max line length and mac os seems to have a max line length of 1024.
See descriptions [here](http://stackoverflow.com/questions/14368168/how-to-cin-a-c-string-1024-characters-via-bash-shell), [here](https://unix.stackexchange.com/questions/204815/terminal-does-not-accept-pasted-or-typed-lines-of-more-than-1024-characters) and [here](https://superuser.com/questions/264407/macosx-10-6-7-cuts-off-stdin-at-1024-chars). 

Try to enter it with `CTRL+D`

**Comment by knaccc** [comment] 2017-04-18 09:54
Thanks, yes the ^D thing did work. Unfortunately, this means the wallet can no longer be used with rlwrap. 

FYI I'm using bash, which I think is the default (echo $SHELL outputs /bin/bash)

When using the bash command line normally, there is no limit. The limit only seems to apply once I start monero-wallet-cli

**Comment by hyc** [comment] 2017-09-20 20:49
Compat with rlwrap should be a non-issue now that readline is natively supported. Can we close this?

**Comment by knaccc** [comment] 2017-09-20 21:46
I just tested with Monero 'Helium Hydra' (v0.11.0.0-release) and I still encounter the 1024 char limit. This is without using rlwrap.

**Comment by hyc** [comment] 2017-09-20 22:01
Was your binary built with readline support?

Either way, since the 1024 character limit is in the kernel's tty driver, not sure there's anything we should be doing with this.

**Comment by knaccc** [comment] 2017-09-21 05:46
I'm not using binaries I built myself, I'm just using the binaries I downloaded directly from the web site. 

I guess therefore that deciding whether to close this bug or not depends on whether it is deemed important to be able to send to more than 9 recipients in the same transaction in the CLI.

**Comment by hyc** [comment] 2017-09-21 07:02
I didn't ask whether you built them yourself. I asked whether it had readline support. Apparently the answer to that is no.

Fyi, readline doesn't use cooked terminal mode, so this problem would go away if readline was in use. Next question is why the official binaries aren't using readline on OSX.

**Comment by moneromooo-monero** [comment] 2017-09-21 07:43
Probably because it's autodetected, and so fluffypony never realized it wasn't being picked up.

**Comment by selsta** [comment] 2018-12-07 12:52
macOS binaries use readline now, this can be closed.

**Comment by dEBRUYNE-1** [comment] 2018-12-07 12:53
+resolved

**Closed** 2018-12-07 12:57 UTC
Labels: resolved
