### ISSUE TITLE
Specifying a hostname instead of an IP address for --tx-proxy causes daemon to abort

### ISSUE THREAD

**Issue by comminutus** [monero-project/monero#8591] opened 2022-09-23 18:41 UTC
I am using docker-compose to setup a node with tor.  The monerod daemon runs in a ubuntu container while tor runs on an alpine container, both of them inside the same Docker network.

If I specify `--tx-proxy tor,<tor hostname>:<tor port>,10` (in my case the tor hostname is 'tor', so I use `--tx-proxy tor,tor:9050,10`, the daemon aborts with these messages:
```
E Invalid ipv4:port given for --tx-proxy
E Failed to handle command line
I Deinitializing core...
```

If I specify the IP address given to the tor instance by Docker's networking (`--tx-proxy tor,192.168.176.2:9050,10`) it works fine.  `dig`/`nslookup` on the 'tor' hostname inside the container running monerod works fine.

The trouble with specifying the IP address is orchestration.  I have to explicitly setup a network and a specific IP address known for tor before I launch the docker-compose file.

**Comment by selsta** [comment] 2022-09-23 18:44
Duplicate of https://github.com/monero-project/monero/issues/7963, maybe you can add your comment to it?

**Comment by comminutus** [comment] 2022-09-23 18:50
Thanks @selsta , for some reason when I searched for issues I didn't see this one.

**Comment by comminutus** [comment] 2022-09-23 18:51
duplicate of #7963

**Closed** 2022-09-23 18:54 UTC
