### ISSUE TITLE
Error : Segmentation fault in private testnet

### ISSUE THREAD

**Issue by 19231224lhr** [monero-project/monero#8821] opened 2023-04-11 04:38 UTC
These days I'm learning Monero and try to study how to use private testnet, I found an example by [moneroexamples](https://github.com/moneroexamples) which is https://github.com/moneroexamples/private-testnet.
By its steps, I start to develop a private testnet(No data syncing is required since this is a private test network).But I met some questions, Here are the details.

### First, I Created two wallets:
`wallet01`：
```shell
monero-wallet-cli --testnet --generate-new-wallet ~/testnet/wallet_01.bin  --restore-deterministic-wallet --electrum-seed="sequence atlas unveil summon pebbles tuesday beer rudely snake rockets different fuselage woven tagged bested dented vegan hover rapid fawns obvious muppet randomly seasons randomly" --password "" --log-file ~/testnet/wallet_01.log;
```
its address is : `9wviCeWe2D8XS82k2ovp5EUYLzBt9pYNW2LXUFsZiv8S3Mt21FZ5qQaAroko1enzw3eGr9qC7X1D7Geoo2RrAotYPwq9Gm8`
`wallet02`：
```shell
monero-wallet-cli --testnet --generate-new-wallet ~/testnet/wallet_02.bin  --restore-deterministic-wallet --electrum-seed="deftly large tirade gumball android leech sidekick opened iguana voice gels focus poaching itches network espionage much jailed vaults winter oatmeal eleven science siren winter" --password "" --log-file ~/testnet/wallet_02.log;
```
its address is : `9wq792k9sxVZiLn66S3Qzv8QfmtcwkdXgM5cWGsXAPxoQeMQ79md51PLPCijvzk1iHbuHi91pws5B7iajTX9KTtJ4bh2tCh`

So I get two wallets: `wallet_01` and `wallet_02`, Then exit.

### Second, I started two nodes, using:
```shell
monerod --testnet --no-igd --hide-my-port --data-dir ~/testnet/node_01 --p2p-bind-ip 127.0.0.1 --log-level 1 --add-exclusive-node 127.0.0.1:38080  --fixed-difficulty 50 --disable-rpc-ban
```
and
```shell
monerod --testnet --p2p-bind-port 38080 --rpc-bind-port 38081 --zmq-rpc-bind-port 38082 --no-igd --hide-my-port  --log-level 1 --data-dir ~/testnet/node_02 --p2p-bind-ip 127.0.0.1 --add-exclusive-node 127.0.0.1:28080 --fixed-difficulty 50 --disable-rpc-ban
```
So I get two nodes, like this:
`node1`
![image](https://user-images.githubusercontent.com/70199004/231055679-90d154e9-6431-4228-ae00-ab8312053b22.png)
![image](https://user-images.githubusercontent.com/70199004/231055706-e883356c-1229-46fa-a321-2ef8e2e5a84c.png)
`node2`
![image](https://user-images.githubusercontent.com/70199004/231055773-32e77300-020b-4dfc-b711-871460548e05.png)
![image](https://user-images.githubusercontent.com/70199004/231055811-fbe10861-6525-473f-9a98-761e0f814082.png)

### Third, I restart two wallets to connect to nodes:
```shell
monero-wallet-cli --testnet --trusted-daemon --wallet-file ~/testnet/wallet_01.bin --password '' --log-file ~/testnet/wallet_01.log
```
and
```shell
monero-wallet-cli --testnet --daemon-port 38081 --trusted-daemon --wallet-file ~/testnet/wallet_02.bin --password '' --log-file ~/testnet/wallet_02.log
```
However, it will report an Error:`Segmentation fault (core dumped)`
Left is node's and Right is wallet's.
![image](https://user-images.githubusercontent.com/70199004/231056116-08991913-cb1c-4454-931d-919b0f9d426e.png)
the second node has the same error.
But if I restart the node, There has no error and the wallet can connect to the node:
![image](https://user-images.githubusercontent.com/70199004/231056295-a75570ea-cb64-4c0e-9862-6c8aeaa3953a.png)

### Mining also has an error
But then,I want to mine some money to transfer.I use the example's code:
```shell
start_mining 9wviCeWe2D8XS82k2ovp5EUYLzBt9pYNW2LXUFsZiv8S3Mt21FZ5qQaAroko1enzw3eGr9qC7X1D7Geoo2RrAotYPwq9Gm8 1
```
However, It also has an error:
`Wrong address prefix: 53, expected 18 or 19 or 42. Segmentation fault (core dumped)`
![image](https://user-images.githubusercontent.com/70199004/231056562-18473424-9342-47c0-bea2-39d8a3693e62.png)
The second node has the same error.

I dont know how to solve this problem as a new beginner. Thanks for your answer.
My computer is Ubuntu20.04.

**Comment by 19231224lhr** [comment] 2023-04-11 11:11
> Start `monerod` in `gdb` to get a backtrace from the crash. Do you know how to do that or should I post more detailed instructions?

Sorry I don't how to do that. If you can give a detailed instruction , it may be ok!

**Comment by 19231224lhr** [comment] 2023-04-12 05:22
> Install `gdb` and start monerod with the added arguments.
> 
> ```
> sudo apt-get install gdb
> gdb --args ./monerod --testnet --no-igd --hide-my-port --data-dir ~/testnet/node_01 --p2p-bind-ip 127.0.0.1 --log-level 1 --add-exclusive-node 127.0.0.1:38080  --fixed-difficulty 50 --disable-rpc-ban
> ```
> 
> Then enter
> 
> ```
> run
> ```
> 
> it should now start monerod, wait for it to crash and then enter
> 
> ```
> thread apply all bt
> ```
> 
> and post the output here.

Very Thanks. I will test it.

**Comment by 19231224lhr** [comment] 2023-04-12 05:38
> enabling background mining wasn't the issue. user is going to sync a testnet node and just try to start_mining to remove doubts (perhaps its a hardware/resource issue of the virtual machine)

I find that it can run well in the offical testnet...
![image](https://user-images.githubusercontent.com/70199004/231360965-d3c5548d-3d85-446f-8848-58acfa77f8cd.png)

**Comment by selsta** [comment] 2023-04-24 01:27
@Wolf54 that's not a crash like the other person who opened the issue, RandomX just fails to initialize. How much free RAM do you have before clicking on start_mining?

**Comment by selsta** [comment] 2023-04-24 01:58
@Wolf54 which OS are you using? Is this self compiled? If yes, can you reproduce with getmonero.org binaries?

**Comment by selsta** [comment] 2023-04-24 02:10
For some reason it fails to initialize the RandomX cache. You have enough free RAM so it shouldn't be an issue. I don't think prebuilt binaries will help but still worth a try. Have to wait until someone else can reply.

**Comment by selsta** [comment] 2023-04-24 17:07
Another thing you can try is compile randomx-tests and then post the output here.

https://github.com/tevador/RandomX#linux

**Comment by tevador** [comment] 2023-04-25 18:54
If RandomX tests complete without errors, then it's not a cache initialization issue. It could be a bug in monerod, e.g. accidentally passing `NULL` when calling `randomx_init_dataset` due to some race condition.

**Comment by selsta** [comment] 2023-04-27 14:30
Fixed in https://github.com/monero-project/monero/pull/8831

**Closed** 2023-06-06 01:09 UTC
