### ISSUE TITLE
Failed to add genesis block to blockchain

### ISSUE THREAD

**Issue by guile124** [monero-project/monero#5075] opened 2019-01-15 21:21 UTC
node genesis -a cryptonight -t "Born.............!"
It print waiting and:

2019-01-15 20:49:03.589      7f02d8923780  ERROR  cn  src/cryptonote_basic/cryptonote_format_utils.cpp:184  Failed to parse transaction from blob
2019-01-15 20:49:03.589      7f02d8923780  ERROR  default  src/cryptonote_core/cryptonote_tx_utils.cpp:659  failed to parse coinbase tx from hard coded blob
2019-01-15 20:49:03.590      7f02d8923780  ERROR  blockchain  src/cryptonote_core/blockchain.cpp:430  Failed to add genesis block to blockchain

**Comment by moneromooo-monero** [comment] 2019-01-15 22:06
What is: node genesis -a cryptonight -t "Born.............!" ?

**Comment by Zentcash** [comment] 2019-01-15 22:45
Is the genesis node generator,
From this repo: https://github.com/nasa8x/node-genesis-block

**Comment by guile124** [comment] 2019-01-15 22:53
Is the genesis node generator,
From this repo: https://github.com/nasa8x/node-genesis-block

**Comment by moneromooo-monero** [comment] 2019-01-15 23:22
Then it seems to be a problem with that software.

**Comment by PabloB07** [comment] 2019-01-15 23:53
> Then it seems to be a problem with that software.

We have a problem with or without node-gensis-block.. so you have another way to create a genesis? i've created a dummy tx but doesn't work.

**Comment by PabloB07** [comment] 2019-01-16 02:33
> The genesis block is created directly by the code. You should not have to somehow create one yourself. Start monerod and it will seed the new blockchain with the genesis block.

Any example.. please?. thanks.

**Comment by moneromooo-monero** [comment] 2019-01-16 11:14
It's in Blockchain::init, near this comment:
MINFO("Blockchain not loaded, generating genesis block.");
If it doesn't work when using Monero normally, then I can have a look, but for now I'll assume this is this other software that's breaking.

**Comment by NanoAkron** [comment] 2019-01-16 23:18
Dude...why do you think anyone should help out a pump-and-dump coin project for free?

**Comment by PabloB07** [comment] 2019-01-17 22:51
> Dude...why do you think anyone should help out a pump-and-dump coin project for free?

Do you have any problem with that?..

**Comment by PabloB07** [comment] 2019-01-18 10:21
Well thanks for all @moneromooo-monero :) , the problem is not fixed anyways... :/

**Comment by moneromooo-monero** [comment] 2019-01-18 10:49
Well, if it's ours, it'll get fixed. But it seems to be some other software trrying to stuff an incorrect genesis block in there. Try dumping the genesis block, then comparing to the one you see on a monero block explorer. If it's the same, then it's a monero bug. If it's not the same, then it's a "other software" bug.

**Comment by PabloB07** [comment] 2019-01-20 23:35
> Well, if it's ours, it'll get fixed. But it seems to be some other software trrying to stuff an incorrect genesis block in there. Try dumping the genesis block, then comparing to the one you see on a monero block explorer. If it's the same, then it's a monero bug. If it's not the same, then it's a "other software" bug.

Thanks, i try it! i closed this issue.

**Comment by dEBRUYNE-1** [comment] 2019-01-21 07:59
+invalid

**Closed** 2019-01-21 08:01 UTC
Labels: invalid
