### ISSUE TITLE
CLI crashes if ledgerwaller runs account new

### ISSUE THREAD

**Issue by krtschmr** [monero-project/monero#3958] opened 2018-06-08 06:34 UTC
Trying to create a new account which apparently isn't supported by ledger (yet). 

Freezes the  CLI. Win10.

Maybe for 0.12.3 we can see which features are already supported and then just disable commands that ain't supported?

**Comment by stoffu** [comment] 2018-06-08 07:32
The `account new` command works for me with OSX. I think it's supported.

**Comment by moneromooo-monero** [comment] 2018-06-08 07:40
Send a stack trace for the crash. Not sure how for Window though.

**Comment by VanSenpai** [comment] 2018-06-08 22:31
account new worked on Windows 10. Took about 1 minute for CLI to return.

**Comment by tficharmers** [comment] 2018-06-19 14:52
I created a new account and it was successful. I then created a 2nd account and after a few minutes the CLI was unresponsive and CTRL + C wouldn't quit. I unplugged the Ledger and reinitialized it and because I hadn't saved anything, I had to setup the first account again.

**Comment by stoffu** [comment] 2018-06-20 02:58
That stall is caused by the default subaddress lookahead sizes being too large. I've made a patch that lowers the default when creating a wallet with Ledger (https://github.com/monero-project/monero/pull/3921/commits/758072d2c095775ab5af533007b8f766eb026c91), which is yet to be merged. In the meantime, you can add this option `--subaddress-lookahead 5:20` to the command `monero-wallet-cli --generate-from-device`.

**Comment by moneromooo-monero** [comment] 2018-07-03 14:39
Was there a crash then ?
The delay fix was merged. If there's no further claim of a crash, I'll close as fixed.

**Comment by tficharmers** [comment] 2018-07-03 16:17
@stoffu Yes I could see that being the case. I actually generated my wallet with:

`--subaddress-lookahead 5:200`

I actually just tried it again and was able to create two accounts consecutively without it dying.

**Comment by moneromooo-monero** [comment] 2018-07-12 22:15
+resolved

**Closed** 2018-07-12 23:16 UTC
Labels: resolved
