### ISSUE TITLE
`scan_tx` causes extra transfers with fee=0

### ISSUE THREAD

**Issue by woodser** [monero-project/monero#8531] opened 2022-08-23 13:24 UTC
Calling `scan_txs` with already scanned tx ids causes `get_transfers` to start returning erroneous transfers with fee=0, which causes downstream errors reconciling the information reported from the wallet for libraries / applications.

It's accompanied with this output in monero-wallet-rpc, but this is probably expected:

2022-08-21 13:21:40.823	E Public key fdfa07f837a16a90d733fceb55581c0c0f8c6ba3574ef928738512083c65622a from received 35.173300860152 output already exists with spent 35.173300860152 in tx <ea6c9edae116224a5494e78bbeafc5508cc11734bc8e6e36a9784c6b7dcf160f>, received output ignored

**Comment by j-berman** [comment] 2022-09-10 03:06
I'm not seeing how to repro extra transfers with fee=0, but I can repro extra transfers with amount=0 and see what's causing that.

Are you certain the issue is extra transfers with fee=0 and not amount=0?

[This code](https://github.com/j-berman/monero/commit/7db2aa914e252c6a1bd83e80c3accb0d36e40e2a) should prevent the amount=0 issue, though I don't think it's a complete solution as is.

**Comment by selsta** [comment] 2024-01-03 05:06
Should be fixed with #8566

**Closed by selsta** 2024-01-03 05:06 UTC
