### ISSUE TITLE
All monero-wallet-rpc methods error with "wrong number of additional derivations" on first use with new wallet

### ISSUE THREAD

**Issue by MatteBru** [monero-project/monero#4127] opened 2018-07-10 20:56 UTC
UPDATE: I have also tested this with get_balance, and this pattern of warnings/errors appears the same way.

*this all happens on stagenet on code compiled from master on July 5*

Upon creating a new view-only wallet, starting monero-wallet-rpc, and running export_outputs, I am getting an error ```wrong number of additional derivations``` both in the response to my rpc request, and in the logfile. It is also surrounded by many ```The same transaction pubkey is present more than once, ignoring extra instance``` messages. If I change nothing, and send the same request, it seems to work just fine. This happens both when the wallet has been funded after creation, and when it has no tx history.

Example section from log file:

```
2018-07-10 20:17:53.055     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:3965     Loaded wallet keys file, with public address: 52e3kyPej6a6dPTu2fGpB38NGykxdSzuy7RtWivLgnsw3n3LZPXGmDXGdLHAEvCrqNHoWGbMkTZvjZYGMvzkj1q$
2018-07-10 20:18:02.086     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:02.086     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:04.089     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:07.501     7f8f8efc4780        WARN    10mwallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:07.503     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:07.503     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:07.670     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:08.059     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:08.267     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:08.484     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:08.650     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:08.651     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:08.850     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:13.046     7f8f8efc4780        ERROR   cn      src/cryptonote_basic/cryptonote_format_utils.cpp:666    wrong number of additional derivations
2018-07-10 20:18:13.048     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:13.048     7f8f8efc4780        WARN    wallet.wallet2  src/wallet/wallet2.cpp:1199     The same transaction pubkey is present more than once, ignoring extra instance
2018-07-10 20:18:13.576     7f8f8efc4780        INFO    global  contrib/epee/include/net/http_server_impl_base.h:76     Binding on 0.0.0.0:38033
allet/wallet2.c8:13.576     7f8f8efc4780        WARN    wallet.rpc      src/wallet/wallet_rpc_server.cpp:3250   Starting wallet RPC server
```

It is not really clear to me why either of the above messages are being displayed, or what they even mean?

Sorry if there is not enough info here, if more is required, I'll be happy to oblige.

I also am wondering if at least the "same transaction pubkey" message has to do with PR https://github.com/monero-project/monero/pull/4117?

**Comment by phire** [comment] 2018-07-10 23:08
There is a malformed transaction on the stagenet blockchain.

As your wallet scans over it, it throws a few warnings/errors but nothing bad happens. It's safe to ignore them.

**Comment by MatteBru** [comment] 2018-07-11 11:50
And this error is caused by the same thing?

```
2018-07-10 20:18:13.046     7f8f8efc4780        ERROR   cn      src/cryptonote_basic/cryptonote_format_utils.cpp:666    wrong number of additional derivations
```

**Comment by moneromooo-monero** [comment] 2018-08-17 15:11
Yes, and did you try to actually scan the whole blockchain (ie, from seed, and don't give a refresh height/date) ?

**Comment by MatteBru** [comment] 2018-08-17 20:52
You'll have to forgive me as the situation is not so fresh in my mind anymore, but I am almost positive that I did not provide a height to begin scanning. If I remember correctly it defaults to height 0, so I would have been scanning the whole blockchain. I followed phire's advice, and did not seem to suffer any consequences so I kind of just let it go.

**Comment by moneromooo-monero** [comment] 2018-08-17 22:56
Yes, it's ignorable and not a bug, I'll close this then.

+invalid

**Closed** 2018-08-17 23:00 UTC
Labels: invalid
