### ISSUE TITLE
viewonly wallet showing different balance to spend wallet

### ISSUE THREAD

**Issue by 4Reallive** [monero-project/monero#2327] opened 2017-08-22 12:59 UTC
I have a view only wallet showing a different balance to the spend wallet.

I have rescan_bc and refreshed the wallet.
Both wallets are syncing on the same node.
I suspect that the view-only wallet is not detecting the spends as on the rescan i only see purple (spends) on the spend wallet and only green (received) on the view only.

I thought that i had a surprise payday and people may freak out when they see their wallet in credit when it is not.

What are the best diagnostics i can provide so that you can see the failure, I am technically very capable and see myself contributing in future.

Thanks for all your hard work on this so far, this is an amazing project.

**Comment by expez** [comment] 2017-08-22 14:09
> I suspect that the view-only wallet is not detecting the spends as on the rescan i only see purple (spends) on the spend wallet and only green (received) on the view only.

This is true and it's working as intended.  You need to read about key images and how to export and import them into your view only wallet so you can keep it up to date with spending.

**Comment by moneromooo-monero** [comment] 2017-08-22 17:44
Closing, please reopen if it's still wrong after importing key images.

+invalid

**Closed** 2017-08-22 17:48 UTC
Labels: invalid
