### ISSUE TITLE
Brazilian Portuguese supporte

### ISSUE THREAD

**Issue by EvertonMelo** [monero-project/monero#2152] opened 2017-07-06 04:27 UTC
add a file language Brazilian Portuguese, 
path:  monero/translations/

**Comment by moneromooo-monero** [comment] 2017-07-06 11:08
See the file README.i18n, which details what is needed in order to get a new language translation.
Note that this is only for monero-wallet-cli, as I think monero-wallet-gui already has a Brazilian translation (or at least a Portuguese one, which I think is kinda mixed pt/pt_BR).  Tracking for the GUI is at https://github.com/monero-project/monero-core/

**Comment by EvertonMelo** [comment] 2017-07-07 19:29
Thank you.

**Comment by moneromooo-monero** [comment] 2017-10-03 11:10
I'm going to close this, as it's not a bug. If you want to add a pt_BR translation, please feel free.

+invalid

**Closed** 2017-10-03 11:12 UTC
Labels: invalid
