### ISSUE TITLE
Stagenet node syncing bad chain

### ISSUE THREAD

**Issue by du2zy** [monero-project/monero#5227] opened 2019-03-04 13:34 UTC
Hello!

My stagenet node stops syncing at 276916 block. It has not updates about last 6 hours. But I see only 273336 blocks in explorer.

It strange situation. Can anybody explain, what it means?

**Comment by du2zy** [comment] 2019-03-04 16:02
I found a line in the log:
```
2019-03-04 15:27:36.957	[P2P7]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:310	[46.101.93.177:37020 INC] Sync data returned a new top block candidate: 128431 -> 276916 [Your node is 148485 blocks (103 days) behind] 
```
I was DROP this IP with iptables. After it seems synchronization has returned to normal (Last block in https://community.xmr.to/explorer/stagenet/ explorer and last block in my log are equals). 

```
2019-03-04 15:56:44.318	[P2P3]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1179	[***]  Synced 137631/273421 (50% 135790 blocks remaining)
```

What it means? I was connected to bad node with fake blockchain? It is possible to protect my test node in future?

**Comment by moneromooo-monero** [comment] 2019-03-04 18:54
There is nothing suggesting a fake blockchain here.
Try with #5225

**Comment by moneromooo-monero** [comment] 2019-03-04 18:55
Or with current release-v0.13 branch (this is what will be the future 0.14.0.2), whch already has that patch.

**Comment by du2zy** [comment] 2019-03-04 19:11
I had similar problem with v0.13.0.4 a few days ago.
Do you have an updated precompiled binaries with this fix (any branch)? I don't want to compile it.
What plans about 0.14.0.2 release? Will it be distributed as binary files? What is the timeline?
Thanks for answers.

**Comment by du2zy** [comment] 2019-03-04 19:15
Does this problem only occur in stagenet?
Does this need to be fixed for Mainnet too?

**Comment by moneromooo-monero** [comment] 2019-03-04 20:16
There will be prebuilt binaries soon. Probably within a day or two. The problem is that once you've gone on a particular version past a consensus fork, you can't reorg back past the block where the consensus rules change. The patch fixes this. Once you have the patch, it works for stagenet as well as mainnet and testnet.

**Comment by moneromooo-monero** [comment] 2019-03-08 00:54
There are 0.14.0.2 binaries now on https://ww.getmonero.org/downloads/

**Comment by moneromooo-monero** [comment] 2019-03-16 22:19
Can you sync to the correct chain now with 0.14.0.2 ?

**Comment by moneromooo-monero** [comment] 2019-03-31 19:01
ping

**Comment by moneromooo-monero** [comment] 2019-04-17 12:06
I'll close as fixed in a few days if there's no more comment.

**Comment by moneromooo-monero** [comment] 2019-04-23 15:34
+resolved

**Closed** 2019-04-23 15:41 UTC
Labels: resolved
