### ISSUE TITLE
Fails to compile against musl libc

### ISSUE THREAD

**Issue by ghost** [monero-project/monero#2030] opened 2017-05-16 01:09 UTC
Running Void Linux, with musl libc. Build fails due to musl's lack of execinfo.h.

```
In file included from /tmp/monero-0.10.3.1/contrib/epee/include/misc_log_ex.h:61:0,
                 from /tmp/monero-0.10.3.1/contrib/epee/include/serialization/keyvalue_serialization.h:31,
                 from /tmp/monero-0.10.3.1/src/p2p/p2p_protocol_defs.h:34,
                 from /tmp/monero-0.10.3.1/src/common/util.h:43,
                 from /tmp/monero-0.10.3.1/src/common/base58.cpp:39:
/tmp/monero-0.10.3.1/external/easylogging++/easylogging++.h:345:25: fatal error: execinfo.h: No such file or directory
 #   include <execinfo.h>
                         ^
compilation terminated.
make[3]: *** [src/common/CMakeFiles/obj_common.dir/build.make:63: src/common/CMakeFiles/obj_common.dir/base58.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:486: src/common/CMakeFiles/obj_common.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:141: all] Error 2
make: *** [Makefile:59: release-all] Error 2

```

**Comment by danrmiller** [comment] 2017-05-16 19:20
This is the same case for OpenBSD. 

https://build.getmonero.org/builders/monero-static-openbsd-amd64/builds/4/steps/compile/logs/stdio

There are several platforms without execinfo. I think @moneromooo-monero said its used by easylogging to get stack trace info and so maybe we should just include it on linux.

**Comment by moneromooo-monero** [comment] 2017-05-17 19:48
Can you try replacing it with elf.h and see if that builds ?

**Comment by danrmiller** [comment] 2017-05-21 21:02
@moneromooo-monero OpenBSD doesn't have an elf.h but it does have sys/exec_elf.h, which looks about the same. If I use that instead of execinfo.h I get "use of undeclared identifier" errors for val, backtrace, and backtrace_symbols.

@wang-gretzky What about on Void Linux?

**Comment by moneromooo-monero** [comment] 2017-05-22 07:30
Do you see these symbols anywhere ? If not, then I guess this can be disabled for that platform.

**Comment by danrmiller** [comment] 2017-06-11 23:53
> Do you see these symbols anywhere ?

No.

**Comment by moneromooo-monero** [comment] 2017-07-31 20:16
Does this work ? https://github.com/monero-project/monero/pull/2235

**Comment by misery** [comment] 2017-08-01 06:18
I added a package to AlpineLinux. Alpine uses musl: https://git.alpinelinux.org/cgit/aports/tree/testing/monero
There are some glitches so enable musl support. See the patches.

**Comment by moneromooo-monero** [comment] 2017-08-01 09:46
Interesting, I thought __has_include was a CLANG only thing. Looks like it's in GCC 5 now.
Also, ideally, the CMakeLists.txt patch should be unnecessary if the easylogging one is applied. What are the errors if it is omitted ?

**Comment by misery** [comment] 2017-08-01 10:06
Just to avoid a lot of warnings

```
In file included from /home/andre/aports/testing/monero/src/monero-0.10.3.1/contrib/epee/include/misc_log_ex.h:61:0,
                 from /home/andre/aports/testing/monero/src/monero-0.10.3.1/contrib/epee/include/serialization/keyvalue_serialization.h:31,
                 from /home/andre/aports/testing/monero/src/monero-0.10.3.1/src/cryptonote_basic/cryptonote_basic.h:46,
                 from /home/andre/aports/testing/monero/src/monero-0.10.3.1/src/blockchain_utilities/bootstrap_file.h:37,
                 from /home/andre/aports/testing/monero/src/monero-0.10.3.1/src/blockchain_utilities/blockchain_export.cpp:29:
/home/andre/aports/testing/monero/src/monero-0.10.3.1/external/easylogging++/easylogging++.h:205:11: warning: #warning "Stack trace not available for this compiler"; [-Wcpp]
 #         warning "Stack trace not available for this compiler";
           ^~~~~~~
```

_has_include will be in C++17

**Comment by moneromooo-monero** [comment] 2017-08-01 13:10
Ah, that makes sense, thanks.

**Comment by moneromooo-monero** [comment] 2017-08-02 10:11
I've updated the patch to remove the warning except once.

**Comment by danrmiller** [comment] 2017-10-12 04:50
This is what I get with #2235. I wonder if we might revive it since #2249 has been abandoned. I can give you access to an openbsd box.

```[ 43%] Building CXX object external/easylogging++/CMakeFiles/easylogging.dir/easylogging++.cc.o
In file included from /home/vagrant/monero/external/easylogging++/easylogging++.cc:18:
/home/vagrant/monero/external/easylogging++/easylogging++.h:216:13: warning: "Stack trace not available for this compiler"; [-W#warnings]
#           warning "Stack trace not available for this compiler";
            ^
/home/vagrant/monero/external/easylogging++/easylogging++.cc:718:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
/home/vagrant/monero/external/easylogging++/easylogging++.cc:1038:8: error: use of undeclared identifier 'val'
  if ((val == nullptr) || ((strcmp(val, "") == 0))) {
       ^
/home/vagrant/monero/external/easylogging++/easylogging++.cc:1038:36: error: use of undeclared identifier 'val'
  if ((val == nullptr) || ((strcmp(val, "") == 0))) {
                                   ^
/home/vagrant/monero/external/easylogging++/easylogging++.cc:1052:22: error: use of undeclared identifier 'val'
  return std::string(val);
                     ^
2 warnings and 3 errors generated.
```

**Comment by moneromooo-monero** [comment] 2017-10-12 08:08
Sure, I'll fix if I have access to one.

**Comment by moneromooo-monero** [comment] 2017-12-02 09:15
I think it's fixed with ston1th's latest commits.

**Comment by ston1th** [comment] 2017-12-04 22:57
@moneromooo-monero unfortunately my commits just fixed the OpenBSD part, not the musl libc.

I just fired an Alpine Linux VM to test some solutions (maybe a generic one) using `__has_include` and/or `__GNU_LIBRARY__`.

**Comment by danrmiller** [comment] 2017-12-05 16:24
@ston1th We have a builder for alpine, looks like its close, needs a -lz maybe? 
https://build.getmonero.org/builders/monero-static-alpine-3.5-x86_64/builds/1146/steps/compile/logs/stdio

**Comment by ston1th** [comment] 2017-12-05 17:37
@danrmiller 
Huh I'm bit confused now.
I tried to build master on Alpine 3.6 and got the `<execinfo.h>` error. I try a clean VM later on.

Anyway.. yes I think there needs to be a `-lz`.
But I'm not sure this will fix these two errors:
```
[ 91%] Linking CXX executable ../../bin/monero-wallet-rpc
../../external/easylogging++/libeasylogging.a(easylogging++.cc.o): In function `el::base::debug::StackTrace::generateNew()':
easylogging++.cc:(.text+0xc7da): undefined reference to `backtrace'
easylogging++.cc:(.text+0xc7e6): undefined reference to `backtrace_symbols'
```

@moneromooo-monero I looked through https://github.com/monero-project/monero/pull/2235 and I would like to add those two ([#2235-R17](https://github.com/monero-project/monero/pull/2235/files#diff-863b4856897c6b87c318d0d23a841411R17), [#2235-R212](https://github.com/monero-project/monero/pull/2235/files#diff-8d1543a579ef452b6020555d522ff978R212)) so we don't spam the build logs with warnings if execinfo is not available.

**Comment by moneromooo-monero** [comment] 2017-12-10 18:21
2900 is merged.

**Comment by moneromooo-monero** [comment] 2018-10-01 11:38
Is this still happening ?

**Comment by andypost** [comment] 2018-10-23 22:44
meanwhile it happened again http://build.alpinelinux.org/buildlogs/build-edge-armhf/testing/monero/monero-0.13.0.2-r0.log
```
[  5%] No download step for 'generate_translations_header'
-- The most recent tag was at c93942e1ed
-- You are ahead of or behind a tagged release
In file included from /home/buildozer/aports/testing/monero/src/monero-0.13.0.2/external/easylogging++/easylogging++.cc:18:
/home/buildozer/aports/testing/monero/src/monero-0.13.0.2/external/easylogging++/easylogging++.h:216:10: warning: #warning "Stack trace not available for this compiler"; [-Wcpp]
 #        warning "Stack trace not available for this compiler";
          ^~~~~~~
```

**Comment by andypost** [comment] 2018-10-24 04:19
> apk add libexecinfo-dev
this also does not help and without patch it fails on linking
```
[ 80%] Linking CXX executable ../../bin/monero-blockchain-export
/usr/lib/gcc/x86_64-alpine-linux-musl/8.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: ../../external/easylogging++/libeasylogging.a(easylogging++.cc.o): in function `el::base::debug::StackTrace::generateNew()':
easylogging++.cc:(.text+0xd51d): undefined reference to `backtrace'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: easylogging++.cc:(.text+0xd529): undefined reference to `backtrace_symbols'
collect2: error: ld returned 1 exit status
```

**Comment by cornfeedhobo** [comment] 2018-10-24 04:41
I can confirm this, but I think the issue might be [upstream](https://github.com/muflihun/easyloggingpp/issues/540). Currently using a patch as a workaround.

**Comment by cornfeedhobo** [comment] 2019-12-06 16:06
We're back to this failing for `0.15.x.x`. I haven't figured out a patch yet.

**Comment by cornfeedhobo** [comment] 2019-12-06 21:59
This disables the stack traces. Best compromise I can come up with right now.

`export CXXFLAGS="${CXXFLAGS} -DELPP_FEATURE_CRASH_LOG"`

**Comment by moneromooo-monero** [comment] 2019-12-18 03:09
This enables crash logs. Did you mean -U ?

**Comment by jbg** [comment] 2020-03-01 08:07
It builds successfully on Alpine with `-DELPP_FEATURE_CRASH_LOG`, so I guess it does disable crash logs @moneromooo-monero

**Comment by codebling** [comment] 2021-01-09 07:45
For posterity (because this issue comes up first in a number of search results for musl-related linking errors, especially related to easylogging), the switch that did it for me was `-DSTACK_TRACE:BOOL=OFF` (every other patch or switch suggested in this thread either did not work or gives a 404).

Sorry for the necrobump

**Comment by cornfeedhobo** [comment] 2021-02-01 16:17
@codebling Can you elaborate on "not work"? I'm also confused by the 404 comment.

FWIW, I've been successfully building and running for over a year with disabled crash logs.

**Comment by codebling** [comment] 2021-02-01 17:44
@cornfeedhobo sorry the 404 was for some of the links posted which purportedly contained solutions. Many didn't work. 

"Not work" meant could not get EasyLogging++ to compile and link. This was specifically about EL++, not specifically related to Monero compilation at all, and in that sense was a bit of a thread hijack. Though it's very possible that Monero will run into the same issues next time the project upgrades to a newer version of EL++.

**Comment by cornfeedhobo** [comment] 2021-02-01 17:56
@codebling understood. Thanks for clarifying.

**Comment by dimandzhi** [comment] 2022-01-06 19:35
> apk add libexecinfo-dev

Compiling with both `-lexecinfo` and `-ldl` did it for me. I've lost the source where I've got this idea. Hope it helps anyone.

**Comment by cornfeedhobo** [comment] 2022-01-17 11:30
@danrmiller I think this issue can be closed with comments left open.

**Closed** 2022-01-17 19:19 UTC
