### ISSUE TITLE
use wallet rpc how to create a cold wallet and a hot wallet

### ISSUE THREAD

**Issue by binlaniua** [monero-project/monero#6277] opened 2020-01-01 05:22 UTC
just find "save_watch_only" command in cli,  wallet rpc have same like it

**Comment by moneromooo-monero** [comment] 2020-01-01 16:07
You use the generate_from_keys RPC. See tests/functional_tests/cold_signing.py for an example.

Not a bug, closing.

+invalid

**Closed** 2020-01-01 16:09 UTC
Labels: invalid
