### ISSUE TITLE
Sending to a standard address without specifying a payment ID still gives prompt about using subaddress instead of encrypted payment ID

### ISSUE THREAD

**Issue by sethsimmons** [monero-project/monero#6523] opened 2020-05-12 20:40 UTC
When sending from monero-wallet-cli to any non-subaddress, and not specifying a payment ID of any kind, once the transaction is confirmed monero-wallet-cli warns the user with the following text:

`NOTE: this transaction uses an encrypted payment ID: consider using subaddresses instead`

This text shouldn't appear when not specifying a payment ID, AFAICT.

**Comment by GoodEn0ugh** [comment] 2020-05-12 20:49
I also tested this with another external 4-address and got the same response upon confirmation of the Tx.

**Comment by erciccione** [comment] 2020-05-13 09:59
AFAIK all transactions have a dummy encrypted payment ID now. Could that be the reason for the warning?

**Comment by selsta** [comment] 2020-05-13 10:00
It should not trigger on a dummy PID.

**Comment by GoodEn0ugh** [comment] 2020-05-13 12:16
Yeah, I figured it's being *caused* by the dummy PID, but doesn't seem like that's intended behavior.
@moneromooo-monero made a patch that I'll try to test out today: https://github.com/moneromooo-monero/bitmonero/commit/a90e9bf4cfed3e126751e0c6ec65deacda065d41

**Comment by moneromooo-monero** [comment] 2020-05-13 13:59
https://github.com/monero-project/monero/pull/6527

It was triggering on change, since you can't decrypt it as it's encrypted to the recipient so it could not tell it was a dummy one.

**Comment by moneromooo-monero** [comment] 2020-06-01 11:51
Should be fixed now. Hopefully no special cases left.

**Closed** 2020-07-19 18:18 UTC
