### ISSUE TITLE
is there any sdk that can create transaction and sign hex without rpc api?

### ISSUE THREAD

**Issue by ruanqunfeng** [monero-project/monero#5057] opened 2019-01-09 12:44 UTC
is there any sdk that can create transaction and sign hex without rpc api?

**Comment by jtgrassie** [comment] 2019-01-11 17:38
No. In future, questions to either https://monero.stackexchange.com/ or https://www.reddit.com/r/monerosupport/ please. GitHub issues are for bug/issue tracking, not general Monero questions.

**Comment by moneromooo-monero** [comment] 2019-09-02 11:23
Not a bug report, closing.

+invalid

**Closed** 2019-09-02 12:17 UTC
Labels: invalid
